/*
 * ao_earth.c -- D0 / Aperture / Position / Ground Truth
 *
 * Implementation of the frozen layer. All static data tables are
 * generated by gen_earth_data.py and #included from ao_earth_data.inc:
 *   - ao_op_names[10]                (operator name strings)
 *   - ao_cl_72[10][10]               (TSML: 73-harmony CL table)
 *   - ao_cl_44[10][10]               (44-harmony CL table)
 *   - ao_cl_22[10][10]               (BHML: 28-harmony CL table)
 *   - ao_bumps[11]                   (dissonant CL compositions)
 *   - ao_force_lut[26][5]            (a-z → 5D force vectors)
 *   - ao_d2_op_map[5][2]             (dimension+sign → operator)
 *   - ao_mass[10]                    (concept mass per operator)
 *   - ao_dbc[10][3]                  (Divine27 coordinates)
 *   - ao_words[]                     (571 vocabulary words)
 *   - ao_lattice[10][2][3][3]        (semantic lattice slots)
 *   - ao_micro_order[10]             (lens priority per operator)
 *   - ao_phase_affinity[10]          (preferred TIG phase per op)
 *   - ao_macro_chains[13]            (narrative arc templates)
 *   - ao_reverse_index[]             (531 sorted words for reading)
 *
 * The functions here are thin lookup helpers — no state, no side effects.
 *
 * Copyright (c) 2025-2026 Brayden Sanders / 7Site LLC
 * Licensed under the 7Site Human Use License v1.0
 * See LICENSE file in project root for full terms.
 *
 * FREE for humans for personal/recreational use.
 * NO commercial or government use without written agreement.
 */


#include "ao_earth.h"
#include <string.h>
#include <stdlib.h>
#include <math.h>

/* ══════════════════════════════════════════════════════════════════════
 * Generated Data Tables
 *
 * All data in ao_earth_data.inc is generated by gen_earth_data.py from
 * the Python SEMANTIC_LATTICE, CL tables, and Hebrew force LUT.
 * Regenerate with: python gen_earth_data.py > ao_earth_data.inc
 *
 * Also defines:
 *   static uint8_t ao_bump_lut[10][10] = {0};  (lazy-init bump cache)
 *   static int ao_bump_lut_init = 0;
 * ══════════════════════════════════════════════════════════════════════ */
#include "ao_earth_data.inc"


/* ══════════════════════════════════════════════════════════════════════
 * CL Shell Lookup
 *
 * Returns the correct 10×10 composition table for the given shell:
 *   22 → ao_cl_22 (BHML, 28-harmony, physics/doing)
 *   44 → ao_cl_44 (44-harmony, becoming/evolving)
 *   72 → ao_cl_72 (TSML, 73-harmony, being/measuring)
 *
 * Defaults to ao_cl_44 (Becoming) for unrecognized shells —
 * the middle ground between measuring and computing.
 * ══════════════════════════════════════════════════════════════════════ */

const int8_t (*ao_cl_shell(int shell))[10]
{
    switch (shell) {
        case 22: return ao_cl_22;
        case 44: return ao_cl_44;
        case 72: return ao_cl_72;
        default: return ao_cl_44; /* default to Becoming */
    }
}

/* Compose two operators at a given shell.
 * Out-of-range operators return HARMONY (the absorber — safe default). */
int ao_compose(int a, int b, int shell)
{
    const int8_t (*table)[10] = ao_cl_shell(shell);
    if (a < 0 || a >= AO_NUM_OPS || b < 0 || b >= AO_NUM_OPS)
        return AO_HARMONY;
    return table[a][b];
}


/* ══════════════════════════════════════════════════════════════════════
 * Bump Detection
 *
 * Bumps are the 11 dissonant compositions in the CL — torus corners
 * where the geometry folds. When the heartbeat composes two operators
 * and hits a bump, energy spikes and attention increases.
 *
 * Uses a lazy-initialized 10×10 boolean LUT for O(1) lookup.
 * The LUT is populated on first call from the ao_bumps[11] array.
 * Thread-safe for reads after first initialization.
 * ══════════════════════════════════════════════════════════════════════ */

int ao_is_bump(int row, int col)
{
    if (!ao_bump_lut_init) {
        int i;
        for (i = 0; i < AO_NUM_BUMPS; i++)
            ao_bump_lut[ao_bumps[i].row][ao_bumps[i].col] = 1;
        ao_bump_lut_init = 1;
    }
    if (row < 0 || row >= 10 || col < 0 || col >= 10)
        return 0;
    return ao_bump_lut[row][col];
}


/* ══════════════════════════════════════════════════════════════════════
 * Reverse Voice Lookup (Binary Search)
 *
 * The reverse index is a sorted array of 531+ words. Each entry maps
 * a word back to its semantic lattice position: (operator, lens, phase, tier).
 *
 * Used by the reverse voice pipeline (ao_water.c) to verify what AO
 * reads — words found here are candidates for TRUSTED classification
 * if the D2 physics path agrees.
 *
 * Binary search via stdlib bsearch: O(log n) per lookup.
 * Returns NULL for words not in AO's vocabulary (classified as UNKNOWN).
 * ══════════════════════════════════════════════════════════════════════ */

static int ao_reverse_cmp(const void* key, const void* entry)
{
    return strcmp((const char*)key, ((const AO_ReverseEntry*)entry)->word);
}

const AO_ReverseEntry* ao_reverse_lookup(const char* word)
{
    return (const AO_ReverseEntry*)bsearch(
        word, ao_reverse_index, (size_t)ao_reverse_index_size,
        sizeof(AO_ReverseEntry), ao_reverse_cmp
    );
}


/* ══════════════════════════════════════════════════════════════════════
 * 5D Vector Classification (argmax + sign → operator)
 *
 * Given a 5D force or curvature vector [aperture, pressure, depth,
 * binding, continuity], finds the dimension with the largest absolute
 * magnitude, then maps (dimension, sign) → operator via ao_d2_op_map.
 *
 * Algorithm:
 *   1. Find dim with max |vec[dim]|
 *   2. If max magnitude < 1e-12 → return HARMONY (zero vector = coherence)
 *   3. If vec[dim] >= 0 → return ao_d2_op_map[dim][0] (positive op)
 *   4. If vec[dim] < 0  → return ao_d2_op_map[dim][1] (negative op)
 *
 * This is the fundamental bridge from continuous physics (5D vectors)
 * to discrete algebra (10 operators). Used by both D1 and D2 pipelines.
 * ══════════════════════════════════════════════════════════════════════ */

int ao_classify_5d(const float vec[5])
{
    int best_dim = 0;
    float best_abs = 0.0f;
    int i;

    for (i = 0; i < 5; i++) {
        float a = vec[i] < 0.0f ? -vec[i] : vec[i];
        if (a > best_abs) {
            best_abs = a;
            best_dim = i;
        }
    }

    if (best_abs < 1e-12f)
        return AO_HARMONY; /* zero vector = perfect coherence */

    return vec[best_dim] >= 0.0f
        ? ao_d2_op_map[best_dim][0]
        : ao_d2_op_map[best_dim][1];
}


/* ══════════════════════════════════════════════════════════════════════
 * DBC Class Lookup
 *
 * Returns whether an operator belongs to the Being or Doing class
 * in the Divine27 coordinate system.
 *
 *   BEING (states of existence):
 *     VOID, LATTICE, COLLAPSE, BALANCE, HARMONY, BREATH
 *
 *   DOING (actions, changes):
 *     COUNTER, PROGRESS, CHAOS, RESET
 *
 * Becoming is not a static class — it EMERGES from composing
 * Being with Doing on the CL. That's the whole point of TIG.
 *
 * Used in reverse voice verification for "loose agreement" —
 * two paths that produce operators in the same DBC class are
 * considered partially consistent even if the exact operators differ.
 * ══════════════════════════════════════════════════════════════════════ */

int ao_dbc_class(int op)
{
    switch (op) {
        case AO_VOID:     case AO_LATTICE:  case AO_COLLAPSE:
        case AO_BALANCE:  case AO_HARMONY:  case AO_BREATH:
            return AO_DBC_BEING;
        case AO_COUNTER:  case AO_PROGRESS:
        case AO_CHAOS:    case AO_RESET:
            return AO_DBC_DOING;
        default:
            return AO_DBC_BEING;
    }
}


/* ══════════════════════════════════════════════════════════════════════
 * Histogram Majority (Skip HARMONY Absorber)
 *
 * Finds the most common operator in an array, EXCLUDING HARMONY.
 *
 * Why skip HARMONY? Because HARMONY is the CL absorber — 73 of 100
 * compositions produce it. If we don't skip it, every histogram would
 * be dominated by HARMONY, drowning out the actual signal. The
 * non-HARMONY operators carry the real information about what's happening.
 *
 * Returns AO_HARMONY if the array is empty or all HARMONY (rare but valid —
 * means the signal truly IS pure coherence).
 *
 * Used by:
 *   - Fractal comprehension (word fuses, level fuses)
 *   - Voice compilation (intended operator extraction)
 *   - Chain resonance calculation
 * ══════════════════════════════════════════════════════════════════════ */

int ao_histogram_majority(const int* ops, int n)
{
    int counts[AO_NUM_OPS] = {0};
    int best_op = AO_VOID, best_count = 0;
    int i;

    for (i = 0; i < n; i++) {
        int op = ops[i];
        if (op >= 0 && op < AO_NUM_OPS)
            counts[op]++;
    }

    for (i = 0; i < AO_NUM_OPS; i++) {
        if (i == AO_HARMONY) continue; /* skip absorber */
        if (counts[i] > best_count) {
            best_count = counts[i];
            best_op = i;
        }
    }

    return (best_count == 0) ? AO_HARMONY : best_op;
}
