"""
gen_earth_data.py -- Generate C data tables from Python earth.py

Reads ao.earth and emits ao_earth_data.inc containing:
  - ao_words[] (flat string pool)
  - ao_lattice[10][2][3][3] (word slot index)
  - ao_cl_72/44/22 (CL tables)
  - ao_force_lut (26x5 force vectors)
  - ao_mass (10 mass values)
  - ao_d2_op_map (5x2 operator map)
  - ao_bumps (11 bump positions)
  - ao_dbc (10x3 DBC coordinates)
  - ao_micro_order (10 values)
  - ao_phase_affinity (10 values)
  - ao_macro_chains (13 chains)
  - ao_reverse_index (sorted reverse voice lookup)

Usage: cd Gen9/targets/AO && python src/gen_earth_data.py > src/ao_earth_data.inc
"""

import sys
import os

# Add parent so we can import ao.earth
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))
from ao import earth


def emit_header():
    print("/* Auto-generated by gen_earth_data.py -- DO NOT EDIT */")
    print()


def emit_op_names():
    print("const char* ao_op_names[AO_NUM_OPS] = {")
    for i, name in enumerate(earth.OP_NAMES):
        comma = "," if i < 9 else ""
        print(f'    "{name}"{comma}')
    print("};")
    print()


def emit_cl_table(name, table):
    print(f"const int8_t {name}[10][10] = {{")
    for i, row in enumerate(table):
        vals = ", ".join(f"{v:2d}" for v in row)
        comma = "," if i < 9 else ""
        print(f"    {{ {vals} }}{comma}  /* {earth.OP_NAMES[i]} */")
    print("};")
    print()


def emit_force_lut():
    print("const float ao_force_lut[26][5] = {")
    for i in range(26):
        vec = earth.FORCE_LUT[i]
        vals = ", ".join(f"{v:.1f}f" for v in vec)
        ch = chr(ord('a') + i)
        root = earth.LATIN_TO_ROOT[ch]
        comma = "," if i < 25 else ""
        print(f"    {{ {vals} }}{comma}  /* {ch} = {root} */")
    print("};")
    print()


def emit_d2_op_map():
    print("const int8_t ao_d2_op_map[5][2] = {")
    dim_names = earth.DIMENSIONS
    for i, (pos, neg) in enumerate(earth.D2_OP_MAP):
        comma = "," if i < 4 else ""
        print(f"    {{ {pos:2d}, {neg:2d} }}{comma}  "
              f"/* {dim_names[i]}: +={earth.OP_NAMES[pos]}, -={earth.OP_NAMES[neg]} */")
    print("};")
    print()


def emit_mass():
    print("const float ao_mass[AO_NUM_OPS] = {")
    vals = []
    for op in range(10):
        if op in earth.MASS:
            vals.append(f"{float(earth.MASS[op]):.6f}f")
        else:
            vals.append("0.0f")
    print(f"    {', '.join(vals)}")
    print("};")
    print()


def emit_bumps():
    print(f"const AO_Bump ao_bumps[{len(earth.BUMPS)}] = {{")
    for i, (r, c) in enumerate(earth.BUMPS):
        comma = "," if i < len(earth.BUMPS) - 1 else ""
        print(f"    {{ {r}, {c} }}{comma}")
    print("};")
    print()
    # Also emit the bump LUT for O(1) lookup
    print("static int8_t ao_bump_lut[10][10] = {0};")
    print("static int ao_bump_lut_init = 0;")
    print()


def emit_dbc():
    print("const int8_t ao_dbc[AO_NUM_OPS][3] = {")
    for op in range(10):
        d, b, c = earth.OPERATOR_DBC[op]
        comma = "," if op < 9 else ""
        print(f"    {{ {d}, {b}, {c} }}{comma}  /* {earth.OP_NAMES[op]} */")
    print("};")
    print()


def emit_micro_order():
    # 0 = sf (structure first), 1 = fs (flow first)
    print("const uint8_t ao_micro_order[AO_NUM_OPS] = {")
    vals = []
    for op in range(10):
        order = earth.MICRO_ORDER.get(op, 'sf')
        vals.append("1" if order == 'fs' else "0")
    print(f"    {', '.join(vals)}")
    print("};")
    print()


def emit_phase_affinity():
    # 0 = being, 1 = doing
    print("const uint8_t ao_phase_affinity[AO_NUM_OPS] = {")
    vals = []
    for op in range(10):
        phase = earth.PHASE_AFFINITY.get(op, 'being')
        vals.append("1" if phase == 'doing' else "0")
    print(f"    {', '.join(vals)}")
    print("};")
    print()


def emit_macro_chains():
    chains = list(earth.MACRO_CHAINS.items())
    print(f"const AO_MacroChain ao_macro_chains[{len(chains)}] = {{")
    for i, (name, info) in enumerate(chains):
        ops = info['ops']
        lens = 0 if info['lens'] == 'structure' else 1
        comma = "," if i < len(chains) - 1 else ""
        print(f'    {{ "{name}", {{ {ops[0]}, {ops[1]}, {ops[2]} }}, {lens} }}{comma}')
    print("};")
    print()


def emit_semantic_lattice():
    """Emit the flat word pool and the 4D index table."""
    words = []
    slots = {}  # (op, lens_idx, phase_idx, tier_idx) -> (start, count)

    lens_names = ['structure', 'flow']
    phase_names = ['being', 'doing', 'becoming']
    tier_names = ['simple', 'mid', 'advanced']

    for op in range(10):
        lattice_entry = earth.SEMANTIC_LATTICE.get(op, {})
        for li, lens in enumerate(lens_names):
            lens_data = lattice_entry.get(lens, {})
            for pi, phase in enumerate(phase_names):
                phase_data = lens_data.get(phase, {})
                for ti, tier in enumerate(tier_names):
                    tier_words = phase_data.get(tier, [])
                    start = len(words)
                    count = len(tier_words)
                    for w in tier_words:
                        words.append(w)
                    slots[(op, li, pi, ti)] = (start, count)

    # Emit word pool
    print(f"const char* ao_words[{len(words)}] = {{")
    for i, w in enumerate(words):
        comma = "," if i < len(words) - 1 else ""
        # Escape any quotes in the word
        escaped = w.replace('\\', '\\\\').replace('"', '\\"')
        print(f'    "{escaped}"{comma}')
    print("};")
    print(f"const int ao_total_words = {len(words)};")
    print()

    # Emit index table
    print("const AO_WordSlot ao_lattice[10][2][3][3] = {")
    for op in range(10):
        print(f"    /* {earth.OP_NAMES[op]} */ {{")
        for li, lens in enumerate(lens_names):
            print(f"        /* {lens} */ {{")
            for pi, phase in enumerate(phase_names):
                start, count = slots.get((op, li, pi, 0), (0, 0))
                start1, count1 = slots.get((op, li, pi, 1), (0, 0))
                start2, count2 = slots.get((op, li, pi, 2), (0, 0))
                comma = "," if pi < 2 else ""
                print(f"            /* {phase} */ "
                      f"{{ {{{start}, {count}}}, {{{start1}, {count1}}}, {{{start2}, {count2}}} }}{comma}")
            comma2 = "," if li < 1 else ""
            print(f"        }}{comma2}")
        comma3 = "," if op < 9 else ""
        print(f"    }}{comma3}")
    print("};")
    print()

    return words


def emit_reverse_index(words_used):
    """Emit sorted reverse voice index."""
    # Build reverse mapping: word -> (op, lens, phase, tier)
    reverse = {}
    lens_names = ['structure', 'flow']
    phase_names = ['being', 'doing', 'becoming']
    tier_names = ['simple', 'mid', 'advanced']

    for op in range(10):
        lattice_entry = earth.SEMANTIC_LATTICE.get(op, {})
        for li, lens in enumerate(lens_names):
            lens_data = lattice_entry.get(lens, {})
            for pi, phase in enumerate(phase_names):
                phase_data = lens_data.get(phase, {})
                for ti, tier in enumerate(tier_names):
                    tier_words = phase_data.get(tier, [])
                    for w in tier_words:
                        key = w.lower().strip()
                        if key not in reverse:
                            reverse[key] = (op, li, pi, ti)

    # Sort by string comparison (C strcmp order)
    sorted_entries = sorted(reverse.items(), key=lambda x: x[0])

    print(f"const AO_ReverseEntry ao_reverse_index[{len(sorted_entries)}] = {{")
    for i, (word, (op, lens, phase, tier)) in enumerate(sorted_entries):
        comma = "," if i < len(sorted_entries) - 1 else ""
        escaped = word.replace('\\', '\\\\').replace('"', '\\"')
        print(f'    {{ "{escaped}", {op}, {lens}, {phase}, {tier} }}{comma}')
    print("};")
    print(f"const int ao_reverse_index_size = {len(sorted_entries)};")
    print()


def main():
    emit_header()
    emit_op_names()
    emit_cl_table("ao_cl_72", earth.CL_72)
    emit_cl_table("ao_cl_44", earth.CL_44)
    emit_cl_table("ao_cl_22", earth.CL_22)
    emit_force_lut()
    emit_d2_op_map()
    emit_mass()
    emit_bumps()
    emit_dbc()
    emit_micro_order()
    emit_phase_affinity()
    emit_macro_chains()
    words = emit_semantic_lattice()
    emit_reverse_index(words)


if __name__ == '__main__':
    main()
