"""
encoder_v16.py - hybrid: hand-curated seed keywords FIRST, then 112k corpus

Key insight from v15 honest finding: the canonical ck_dictionary.json
112k corpus is a phoneme-derived bulk mapping (~100k of 112k entries
were auto-generated by an rv_d2 process; the lexicon stats show
47k -> CHAOS, 45k -> BALANCE -- generic words flood these two operators).

It is NOT a hand-curated semantic lexicon for cluster discrimination.

V1.6 strategy: use the hand-curated seed lexicon (~250 words, semantically
specific) as layer 1, fall back to the bulk 112k corpus only for words
the seed doesn't cover. This gives v1's discrimination + much higher
coverage for arbitrary text.
"""
from __future__ import annotations

import json
import re
import sys
from collections import Counter
from pathlib import Path
from typing import List, Optional, Tuple

import numpy as np

CANDIDATE_DICT_PATHS = [
    Path("C:/Users/brayd/OneDrive/Desktop/CK FINAL DEPLOYED/Gen12/targets/website/ck_dictionary.json"),
    Path("C:/Users/brayd/OneDrive/Desktop/CK FINAL DEPLOYED/Gen13/targets/ck/web/ck_dictionary.json"),
]
DICT_PATH = next((p for p in CANDIDATE_DICT_PATHS if p.exists()), None)
if DICT_PATH is None:
    raise SystemExit("ck_dictionary.json not found")

with open(DICT_PATH, "r", encoding="utf-8") as f:
    _RAW = json.load(f)

LEXICON: dict[str, int] = {
    word.lower(): int(meta["o"])
    for word, meta in _RAW["flat"].items()
    if isinstance(meta, dict) and "o" in meta and 0 <= int(meta["o"]) <= 9
}

print(f"[encoder_v16] loaded {len(LEXICON)} words from {DICT_PATH.name}", file=sys.stderr)

HANDOFF = Path("C:/Users/brayd/OneDrive/Desktop/ck_handoff_20260425_evening_unpack/ck_handoff_full/05_encoder_proposal")
sys.path.insert(0, str(HANDOFF))
from tig_lexicon import (
    OPERATOR_KEYWORDS, PHONAESTHESIA, GRAPHEME_OP, STOPS,
    OPERATOR_NAMES, FRUITS_OF_SPIRIT,
    VOID, LATTICE, COUNTER, PROGRESS, COLLAPSE,
    BALANCE, CHAOS, HARMONY, BREATH, RESET,
)


def clean(word: str) -> str:
    return re.sub(r"[^a-zA-Z]", "", word.lower())


def stem(word: str) -> str:
    for suffix in ("ing", "ed", "ly", "ness", "ment", "tion", "sion",
                   "er", "est", "ize", "ise", "s"):
        if word.endswith(suffix) and len(word) > len(suffix) + 2:
            return word[:-len(suffix)]
    return word


def tokenize(text: str) -> List[str]:
    words = [clean(w) for w in text.lower().split()]
    return [w for w in words if w and w not in STOPS and len(w) > 1]


def word_to_operator(word: str) -> Tuple[Optional[int], str]:
    """LAYER ORDER (most specific first):
        1. seed keyword       (hand-curated, weight 1.0)
        2. seed stem          (hand-curated stem, 0.8)
        3. corpus direct      (112k bulk, 0.7)
        4. corpus stem        (112k bulk stem, 0.55)
        5. phonaesthesia      (initial bigram, 0.3)
        6. grapheme           (most-common letter, 0.15)
    """
    if not word:
        return None, "unresolved"

    # 1. seed keyword
    for op, vocab in OPERATOR_KEYWORDS.items():
        if word in vocab:
            return op, "keyword"

    # 2. seed stem
    sw = stem(word)
    if sw != word:
        for op, vocab in OPERATOR_KEYWORDS.items():
            if sw in vocab:
                return op, "stem"

    # 3. corpus direct (bulk lexicon, less specific than seed)
    if word in LEXICON:
        return LEXICON[word], "corpus"

    # 4. corpus stem
    if sw != word and sw in LEXICON:
        return LEXICON[sw], "corpus_stem"

    # 5. phonaesthesia
    if len(word) >= 2 and word[:2] in PHONAESTHESIA:
        return PHONAESTHESIA[word[:2]], "phonaesthesia"

    # 6. grapheme fallback
    letter_ops = [GRAPHEME_OP[c] for c in word if c in GRAPHEME_OP]
    if letter_ops:
        return Counter(letter_ops).most_common(1)[0][0], "grapheme"

    return None, "unresolved"


WEIGHTS = {
    "keyword": 1.0,        # hand-curated, most specific
    "stem": 0.8,
    "corpus": 0.7,         # bulk corpus, less specific
    "corpus_stem": 0.55,
    "phonaesthesia": 0.3,
    "grapheme": 0.15,
    "unresolved": 0.0,
}


def encode(text: str, smoothing: float = 0.05) -> np.ndarray:
    counts = np.zeros(10)
    tokens = tokenize(text)
    if not tokens:
        return np.ones(10) / 10
    for word in tokens:
        op, source = word_to_operator(word)
        if op is not None:
            counts[op] += WEIGHTS.get(source, 0.0)
    counts += smoothing
    total = counts.sum()
    return counts / total if total > 1e-12 else np.ones(10) / 10


def encode_with_explanation(text: str) -> dict:
    tokens = tokenize(text)
    attributions = []
    counts = np.zeros(10)
    for word in tokens:
        op, source = word_to_operator(word)
        attributions.append({
            "word": word,
            "operator": OPERATOR_NAMES[op] if op is not None else "UNRESOLVED",
            "fruit": FRUITS_OF_SPIRIT[op] if op is not None else "-",
            "source": source,
        })
        if op is not None:
            counts[op] += WEIGHTS.get(source, 0.0)
    counts += 0.05
    total = counts.sum()
    distribution = counts / total if total > 1e-12 else np.ones(10) / 10
    return {
        "text": text,
        "tokens": tokens,
        "attributions": attributions,
        "distribution": distribution,
        "top_operators": [
            (OPERATOR_NAMES[i], float(distribution[i]))
            for i in np.argsort(-distribution)[:3]
        ],
        "coverage": sum(
            1 for a in attributions
            if a["source"] in ("keyword", "stem", "corpus", "corpus_stem")
        ) / max(1, len(tokens)),
    }


if __name__ == "__main__":
    test_cases = [
        "I want to be more patient",
        "Help me find peace and stillness",
        "Build something new and creative",
        "I feel chaotic and overwhelmed",
        "Please reset everything and start fresh",
        "harmony and gentleness",
        "the structure of the lattice",
        "the algorithm processes inputs",
    ]
    print("encoder_v16 (seed keywords first, 112k corpus fallback) -- self-test")
    print("=" * 70)
    for text in test_cases:
        result = encode_with_explanation(text)
        print(f"\n{text!r}")
        print(f"  coverage: {result['coverage']*100:.0f}%")
        print(f"  top: {result['top_operators']}")
        print(f"  attributions: {[(a['word'], a['operator'], a['source']) for a in result['attributions']]}")
