"""test_ck_export.py -- regression tests for the export module."""
from __future__ import annotations

import sys
import tempfile
import time
from datetime import date
from pathlib import Path

HERE = Path(__file__).parent.resolve()
sys.path.insert(0, str(HERE))

from ck_export import render_day_markdown, write_day_file  # noqa: E402


class FakeEngine: pass


def test_empty_engine_minimal_output():
    """Engine with no mounted modules should produce a minimal but
    valid markdown report."""
    eng = FakeEngine()
    md = render_day_markdown(eng)
    assert md.startswith("# CK day report —")
    assert "*generated by ck_export.py" in md
    print("T1 PASS: empty engine -> minimal valid markdown")


def test_with_journal_only():
    """Mount only journal; output should include journal section but not others."""
    from ck_journal import Journal
    tmp = Path(tempfile.gettempdir()) / "ck_exp_t2.jsonl"
    if tmp.exists(): tmp.unlink()
    j = Journal(path=tmp)
    j.note("hello today", tags=["test"], mood="ok")
    eng = FakeEngine()
    eng.ck_journal = {"journal": j}
    md = render_day_markdown(eng)
    assert "## Journal" in md
    assert "hello today" in md
    assert "## PC summary" not in md  # not mounted
    j.clear()
    print("T2 PASS: journal-only engine -> journal section, no PC section")


def test_with_bookmark_only():
    from ck_bookmark import Bookmarks
    tmp = Path(tempfile.gettempdir()) / "ck_exp_t3.jsonl"
    if tmp.exists(): tmp.unlink()
    b = Bookmarks(path=tmp)
    b.add("https://example.com/", title="Example", tags=["test"])
    eng = FakeEngine()
    eng.ck_bookmark = {"store": b}
    md = render_day_markdown(eng)
    assert "## Bookmarks" in md
    assert "example.com" in md
    assert "Example" in md
    b.clear()
    print("T3 PASS: bookmark-only engine -> bookmark section")


def test_with_reminder_only():
    from ck_reminder import Reminders
    tmp = Path(tempfile.gettempdir()) / "ck_exp_t4.jsonl"
    if tmp.exists(): tmp.unlink()
    r = Reminders(path=tmp)
    # Three items: one future (PENDING), one past (DUE), one past-then-acked (ACK)
    r.add("future thing", "1h")
    r.add("past thing", time.time() - 100)
    ack_target = r.add("ack thing", time.time() - 200)
    r.acknowledge(ack_target.id)
    eng = FakeEngine()
    eng.ck_reminder = {"store": r}
    md = render_day_markdown(eng)
    assert "## Reminders" in md
    assert "future thing" in md
    assert "past thing" in md
    assert "ack thing" in md
    assert "[ACK]" in md, f"expected [ACK]; md preview:\n{md[:1500]}"
    assert "[PENDING]" in md, f"expected [PENDING]; md preview:\n{md[:1500]}"
    assert "[DUE]" in md, f"expected [DUE]; md preview:\n{md[:1500]}"
    r.clear()
    print("T4 PASS: reminder-only engine -> PENDING + DUE + ACK all rendered")


def test_write_day_file():
    from ck_journal import Journal
    tmp_j = Path(tempfile.gettempdir()) / "ck_exp_t5_j.jsonl"
    if tmp_j.exists(): tmp_j.unlink()
    j = Journal(path=tmp_j)
    j.note("test write", tags=["x"])
    eng = FakeEngine()
    eng.ck_journal = {"journal": j}
    # Write to a temp file
    tmp_out = Path(tempfile.gettempdir()) / "ck_exp_t5_out.md"
    if tmp_out.exists(): tmp_out.unlink()
    path = write_day_file(eng, dest=tmp_out)
    assert path == tmp_out
    assert path.exists()
    content = path.read_text(encoding="utf-8")
    assert "test write" in content
    assert content.startswith("# CK day report")
    # Cleanup
    j.clear()
    tmp_out.unlink()
    print(f"T5 PASS: write_day_file wrote {len(content)} chars to disk")


def test_date_parameter():
    """Past date should produce report with that date in header."""
    from datetime import date as _date, timedelta
    yesterday = _date.today() - timedelta(days=1)
    eng = FakeEngine()
    md = render_day_markdown(eng, target_date=yesterday)
    assert yesterday.isoformat() in md
    print(f"T6 PASS: target_date={yesterday} appears in report header")


def test_journal_only_today():
    """Journal entries from yesterday should NOT appear in today's report."""
    from ck_journal import Journal, JournalEntry
    from datetime import date as _date, timedelta, datetime
    tmp = Path(tempfile.gettempdir()) / "ck_exp_t7.jsonl"
    if tmp.exists(): tmp.unlink()
    j = Journal(path=tmp)
    # Today's entry
    j.note("today note")
    # Manually inject yesterday's
    yesterday_ts = (datetime.combine(_date.today() - timedelta(days=1),
                                       datetime.min.time())).timestamp() + 10000
    yest = JournalEntry(
        ts=yesterday_ts,
        iso="yesterday",
        text="yesterday note",
        operator_path=[1], dominant_op=1, dominant_op_name="LATTICE",
        signature_hash="x",
    )
    j._entries.insert(0, yest)
    eng = FakeEngine()
    eng.ck_journal = {"journal": j}
    md = render_day_markdown(eng)
    assert "today note" in md
    assert "yesterday note" not in md
    j.clear()
    print("T7 PASS: only today's entries appear in today's report")


def test_combined_all_modules():
    """All modules mounted -> all sections render."""
    from ck_journal import Journal
    from ck_bookmark import Bookmarks
    from ck_reminder import Reminders

    tmp = lambda n: Path(tempfile.gettempdir()) / f"ck_exp_t8_{n}.jsonl"
    for n in ("j", "b", "r"):
        p = tmp(n)
        if p.exists(): p.unlink()

    j = Journal(path=tmp("j"))
    j.note("combined test journal")
    b = Bookmarks(path=tmp("b"))
    b.add("https://test.com/", title="Test bookmark")
    r = Reminders(path=tmp("r"))
    r.add("combined test reminder", "1h")

    eng = FakeEngine()
    eng.ck_journal = {"journal": j}
    eng.ck_bookmark = {"store": b}
    eng.ck_reminder = {"store": r}

    md = render_day_markdown(eng)
    for section in ("## Journal", "## Bookmarks", "## Reminders"):
        assert section in md, f"missing section: {section}"
    assert "combined test journal" in md
    assert "Test bookmark" in md
    assert "combined test reminder" in md

    j.clear(); b.clear(); r.clear()
    print("T8 PASS: all three modules mounted -> all three sections render")


def run_all():
    print("=" * 64)
    print("ck_export regression tests")
    print("=" * 64)
    print()
    tests = [test_empty_engine_minimal_output, test_with_journal_only,
              test_with_bookmark_only, test_with_reminder_only,
              test_write_day_file, test_date_parameter,
              test_journal_only_today, test_combined_all_modules]
    n_pass = n_fail = 0
    for t in tests:
        try:
            t()
            n_pass += 1
        except AssertionError as e:
            print(f"  {t.__name__} FAIL: {e}")
            n_fail += 1
        except Exception as e:
            print(f"  {t.__name__} ERROR: {type(e).__name__}: {e}")
            n_fail += 1
    print()
    print(f"RESULT: {n_pass}/{len(tests)} tests passed")
    return n_fail == 0


if __name__ == "__main__":
    sys.exit(0 if run_all() else 1)
