```mermaid
graph LR
  ab_test_full --> ck_audio_compress
  ck_boot_api --> ck_sim_engine
  ck_boot_api --> ck_web_api
  ck_boot_api --> ck_development
  ck_boot_api --> ck_disagreement_tick
  ck_boot_api --> ck_voice_math
  ck_boot_api --> ck_sim_heartbeat
  ck_boot_api --> ck_sim_d2
  ck_boot_api --> ck_meta_lens
  ck_boot_api --> ck_hindsight_replay
  ck_converse --> ck_sim_engine
  ck_converse --> ck_sim_heartbeat
  ck_force9_demo --> ck_audio_compress
  ck_fpga_heartbeat_bridge --> ck_sim_heartbeat
  ck_operator_tests --> ck_sim_heartbeat
  ck_operator_tests --> ck_sim_d2
  ck_pos_tagger --> ck_voice_lattice
  ck_self_evolve --> ck_sim_engine
  ck_self_evolve --> ck_sim_heartbeat
  ck_becoming_grammar --> ck_sim_heartbeat
  ck_becoming_grammar --> ck_voice_lattice
  ck_becoming_grammar --> ck_sim_d2
  ck_concept_spine --> ck_sim_heartbeat
  ck_d1_lattice_builder --> ck_sim_heartbeat
  ck_d2_dictionary_expander --> ck_sim_heartbeat
  ck_d2_dictionary_expander --> ck_sim_d2
  ck_education --> ck_sim_heartbeat
  ck_english_build --> ck_sim_heartbeat
  ck_english_build --> ck_sim_d2
  ck_english_build --> ck_d2_dictionary_expander
  ck_english_build --> ck_sentence_composer
  ck_english_build --> ck_retrieval_engine
  ck_english_build --> ck_self_mirror
  ck_english_build --> ck_btq
  ck_english_build --> ck_sim_btq
  ck_episodic --> ck_sim_heartbeat
  ck_identity --> ck_sim_heartbeat
  ck_journal --> ck_sim_heartbeat
  ck_journal --> ck_sim_d2
  ck_knowledge_bootstrap --> ck_sim_heartbeat
  ck_knowledge_bootstrap --> ck_truth
  ck_knowledge_bootstrap --> ck_world_lattice
  ck_knowledge_bootstrap --> ck_concept_spine
  ck_knowledge_bootstrap --> ck_education
  ck_knowledge_bootstrap --> ck_d2_dictionary_expander
  ck_lexicon --> ck_sim_heartbeat
  ck_lexicon --> ck_sim_d2
  ck_lexicon_bulk --> ck_sim_heartbeat
  ck_memory --> ck_sim_heartbeat
  ck_metalearning --> ck_sim_heartbeat
  ck_network --> ck_sim_heartbeat
  ck_retrieval_engine --> ck_sim_heartbeat
  ck_retrieval_engine --> ck_sim_d2
  ck_self_mirror --> ck_sim_heartbeat
  ck_self_mirror --> ck_sim_d2
  ck_spectrometer_journal --> ck_tig_bundle
  ck_translator --> ck_sim_heartbeat
  ck_truth --> ck_sim_heartbeat
  ck_world_lattice --> ck_sim_heartbeat
  ck_world_lattice --> ck_sim_d2
  ck_algebraic_neural --> ck_sim_heartbeat
  ck_algebraic_proofs --> ck_sim_heartbeat
  ck_attention --> ck_sim_heartbeat
  ck_bible_sense --> ck_sim_heartbeat
  ck_bible_sense --> ck_sim_d2
  ck_bonding --> ck_sim_heartbeat
  ck_btq --> ck_sim_heartbeat
  ck_btq --> ck_sim_d2
  ck_chain_compression --> ck_sim_heartbeat
  ck_clay_codecs --> ck_sdv_safety
  ck_code_translation --> ck_sim_heartbeat
  ck_coherence_action --> ck_sim_heartbeat
  ck_coherence_field --> ck_sim_heartbeat
  ck_coherence_field --> ck_sim_d2
  ck_divine27 --> ck_sim_heartbeat
  ck_divine27 --> ck_sim_d2
  ck_divine_memory --> ck_sim_heartbeat
  ck_dkan_trainer --> ck_sim_heartbeat
  ck_experience --> ck_sim_d2
  ck_experience_index --> ck_sim_heartbeat
  ck_experience_index --> ck_sim_brain
  ck_fibonacci_transform --> ck_sim_heartbeat
  ck_fibonacci_transform --> ck_sim_d2
  ck_formal_theorems --> ck_sdv_safety
  ck_formal_theorems --> ck_coherence_action
  ck_formal_theorems --> ck_tig_bundle
  ck_formal_theorems --> ck_clay_protocol
  ck_formal_theorems --> ck_sim_heartbeat
  ck_formal_theorems --> ck_algebraic_proofs
  ck_fractal_comprehension --> ck_sim_heartbeat
  ck_fractal_comprehension --> ck_sim_d2
  ck_fractal_health --> ck_sim_heartbeat
  ck_gustatory --> ck_sim_heartbeat
  ck_hindsight_replay --> ck_sim_heartbeat
  ck_immune --> ck_sim_heartbeat
  ck_lattice_chain --> ck_sim_heartbeat
  ck_math_translation --> ck_sim_heartbeat
  ck_meta_lens --> ck_sim_heartbeat
  ck_olfactory --> ck_sim_heartbeat
  ck_personality --> ck_sim_heartbeat
  ck_retina --> ck_sim_heartbeat
  ck_retina --> ck_sim_brain
  ck_retina --> ck_sim_d2
  ck_reverse_voice --> ck_sim_heartbeat
  ck_reverse_voice --> ck_voice_lattice
  ck_reverse_voice --> ck_sim_d2
  ck_semantic_index --> ck_sim_heartbeat
  ck_sensorium --> ck_sim_heartbeat
  ck_sensorium --> ck_sim_brain
  ck_sensorium --> ck_swarm
  ck_sensorium --> ck_gpu
  ck_sensorium --> ck_coherence_field
  ck_sensorium --> ck_sensory_codecs
  ck_sensorium --> ck_sim_ears
  ck_sensory_codecs --> ck_sim_heartbeat
  ck_sensory_codecs --> ck_sim_d2
  ck_sim_body --> ck_sim_heartbeat
  ck_sim_brain --> ck_sim_heartbeat
  ck_sim_btq --> ck_sim_heartbeat
  ck_sim_d2 --> ck_sim_heartbeat
  ck_spectral_core --> ck_sim_heartbeat
  ck_swarm --> ck_sim_heartbeat
  ck_swarm --> ck_sim_brain
  ck_swarm_deep --> ck_sim_heartbeat
  ck_swarm_deep --> ck_sim_brain
  ck_swarm_deep --> ck_sim_d2
  ck_taichi_chains --> ck_sim_heartbeat
  ck_tig_security --> ck_sim_heartbeat
  ck_topology_lens --> ck_sdv_safety
  ck_vortex_physics --> ck_sim_heartbeat
  ck_word_expansion --> ck_sim_heartbeat
  ck_action --> ck_sim_heartbeat
  ck_action --> ck_sim_d2
  ck_autodidact --> ck_sim_heartbeat
  ck_autodidact --> ck_sim_d2
  ck_autodidact_runner --> ck_sim_heartbeat
  ck_beam_voice --> ck_sim_heartbeat
  ck_beam_voice --> ck_sim_d2
  ck_beam_voice --> ck_voice_lattice
  ck_breath_engine --> ck_sdv_safety
  ck_breath_engine --> ck_spectrometer
  ck_breath_engine --> ck_tig_bundle
  ck_claude_library --> ck_sim_heartbeat
  ck_claude_library --> ck_sim_d2
  ck_clay_generators --> ck_sdv_safety
  ck_clay_protocol --> ck_sdv_safety
  ck_clay_protocol --> ck_tig_bundle
  ck_clay_protocol --> ck_clay_codecs
  ck_clay_protocol --> ck_clay_generators
  ck_clay_protocol --> ck_sim_heartbeat
  ck_clay_protocol --> ck_vortex_physics
  ck_clay_protocol --> ck_coherence_action
  ck_cloud_btq --> ck_sim_heartbeat
  ck_cloud_curvature --> ck_sim_heartbeat
  ck_cloud_curvature --> ck_sim_d2
  ck_cloud_flow --> ck_sim_heartbeat
  ck_cloud_pfe --> ck_sim_heartbeat
  ck_dialogue --> ck_sim_heartbeat
  ck_dialogue --> ck_sim_d2
  ck_foo_engine --> ck_sdv_safety
  ck_foo_engine --> ck_spectrometer
  ck_force_voice --> ck_sim_heartbeat
  ck_force_voice --> ck_sim_d2
  ck_force_voice --> ck_voice_lattice
  ck_forecast --> ck_sim_heartbeat
  ck_fractal_index --> ck_sim_heartbeat
  ck_fractal_memory --> ck_sim_heartbeat
  ck_fractal_scorer --> ck_sim_heartbeat
  ck_fractal_scorer --> ck_sim_d2
  ck_fractal_voice --> ck_sim_heartbeat
  ck_fractal_voice --> ck_sim_d2
  ck_fractal_voice --> ck_voice_lattice
  ck_game_sense --> ck_sim_heartbeat
  ck_goals --> ck_sim_heartbeat
  ck_language --> ck_sim_heartbeat
  ck_llm_filter --> ck_sim_heartbeat
  ck_llm_filter --> ck_sim_d2
  ck_nce --> ck_sim_heartbeat
  ck_nce --> ck_sim_d2
  ck_organ_clouds --> ck_sim_heartbeat
  ck_prompt_craft --> ck_sim_heartbeat
  ck_pulse_engine --> ck_sim_heartbeat
  ck_rate_engine --> ck_sdv_safety
  ck_rate_engine --> ck_spectrometer
  ck_reasoning --> ck_sim_heartbeat
  ck_rh5_attack --> ck_sdv_safety
  ck_rh5_attack --> ck_clay_protocol
  ck_rh5_attack --> ck_tig_bundle
  ck_rh5_attack --> ck_spectrometer
  ck_semantic_engine --> ck_sim_heartbeat
  ck_semantic_engine --> ck_sim_d2
  ck_sentence_composer --> ck_sim_heartbeat
  ck_sentence_composer --> ck_sim_d2
  ck_sim_engine --> ck_sim_heartbeat
  ck_sim_engine --> ck_sim_brain
  ck_sim_engine --> ck_sim_body
  ck_sim_engine --> ck_sim_led
  ck_sim_engine --> ck_sim_sd
  ck_sim_engine --> ck_body_interface
  ck_sim_engine --> ck_btq
```