# PACKET: evening_handoff_2026_04_23/dictionary_translation.py
"""
TRANSLATION DICTIONARY: Octonion/Vidinli formulas applied to full 10-element TSML.

For each established invariant from their literature, compute TSML's value
(not a reshaped TSML, the actual full 10x10 one).
"""
import numpy as np
from itertools import permutations, combinations
from collections import Counter

N = 10
TSML = [
    [0,0,0,0,0,0,0,7,0,0],
    [0,7,3,7,7,7,7,7,7,7],
    [0,3,7,7,4,7,7,7,7,9],
    [0,7,7,7,7,7,7,7,7,3],
    [0,7,4,7,7,7,7,7,8,7],
    [0,7,7,7,7,7,7,7,7,7],
    [0,7,7,7,7,7,7,7,7,7],
    [7,7,7,7,7,7,7,7,7,7],
    [0,7,7,7,8,7,7,7,7,7],
    [0,7,9,3,7,7,7,7,7,7],
]
BHML = [
    [0,1,2,3,4,5,6,7,8,9],
    [1,2,3,4,5,6,7,2,6,6],
    [2,3,3,4,5,6,7,3,6,6],
    [3,4,4,4,5,6,7,4,6,6],
    [4,5,5,5,5,6,7,5,7,7],
    [5,6,6,6,6,6,7,6,7,7],
    [6,7,7,7,7,7,7,7,7,7],
    [7,2,3,4,5,6,7,8,9,0],
    [8,6,6,6,7,7,7,9,7,8],
    [9,6,6,6,7,7,7,0,8,0],
]

def mul(T, a, b): return T[a][b]

# ============================================================
# 1. VIDINLI SURVIVOR LANGUAGE: Identify "unit" and "conjugation"
# ============================================================
print("="*76)
print("1. VIDINLI VOCABULARY — UNIT, CONJUGATION, REAL/IMAGINARY SPLIT")
print("="*76)
# Vidinli V₇ has:
#   - unit element (u·x = x·u = x for all x) — there is none in TSML (TSML has absorbing, not identity)
#   - conjugation x → x̄ (anti-involution: (xy)̄ = ȳ x̄)
#   - principal 2-planes through unit ≅ ℂ
# TSML has NO unit. This is a structural fact.

# But TSML has a DUAL structure: VOID (0) is left-absorbing, HARMONY (7) is two-sided absorbing.
# The "survivor set" {7, 8, 9} = elements x where TSML[0][x] ≠ 0 (i.e., survive VOID on axis)
print("\nSurvivor analysis: elements x with TSML[0][x] ≠ 0 OR TSML[x][0] ≠ 0")
void_survivors = [x for x in range(N) if TSML[0][x] != 0 or TSML[x][0] != 0]
print(f"  VOID-axis survivors: {void_survivors}")
# In Vidinli, this is like "elements with non-zero real part"
# Non-survivors correspond to "pure imaginary" elements.

# Check: is {7,8,9} really the survivor set?
print(f"  This matches Brayden's intuition: {{7,8,9}} = survivors")

# ============================================================
# 2. THE "REAL PART" — what each element shares with VOID/HARMONY axis
# ============================================================
print("\n2. REAL-PART ANALOG: TSML[0][x] = projection of x onto VOID axis")
print("   TSML[7][x] = projection of x onto HARMONY axis")
print()
print(f"   {'x':>3s} {'TSML[0][x]':>12s} {'TSML[x][0]':>12s} {'TSML[7][x]':>12s}")
for x in range(N):
    print(f"   {x:>3d} {TSML[0][x]:>12d} {TSML[x][0]:>12d} {TSML[7][x]:>12d}")

# ============================================================
# 3. ASSOCIATOR — the Vidinli-characteristic invariant
# ============================================================
print("\n3. ASSOCIATOR [x,y,z] = (xy)z - x(yz) mod 10")
print("   Vidinli: associator vanishes on Jordan part, non-zero on Lie part.")
print("   Octonion: alternating in all 3 args.")
print()
assoc = {}
for x in range(N):
    for y in range(N):
        for z in range(N):
            a = (TSML[TSML[x][y]][z] - TSML[x][TSML[y][z]]) % N
            assoc[(x,y,z)] = a

nonzero_triples = [(x,y,z) for (x,y,z),a in assoc.items() if a != 0]
print(f"   Non-associating triples: {len(nonzero_triples)} of {N**3}")
print(f"   Associator value distribution:")
dist = Counter(assoc.values())
for v in sorted(dist): print(f"     {v:>2d}: {dist[v]:>4d}")

# Which ELEMENTS are involved in non-associating triples?
involvement = Counter()
for (x,y,z) in nonzero_triples:
    involvement[x] += 1
    involvement[y] += 1
    involvement[z] += 1
print(f"   Element involvement in non-associating triples:")
for x in range(N): print(f"     x={x}: involved {involvement[x]} times")

# ============================================================
# 4. PRINCIPAL 2-PLANES AND 3-PLANES
# ============================================================
print("\n4. PRINCIPAL 2-PLANES (Vidinli: each ≅ ℂ): subalgebras generated by pairs")
def subalg(gens, T):
    S = set(gens); changed = True
    while changed:
        changed = False; new = set()
        for a in S:
            for b in S:
                v = T[a][b]
                if v not in S: new.add(v)
        if new: S |= new; changed = True
    return S

pp_sizes = Counter()
for x in range(N):
    for y in range(x+1, N):
        sz = len(subalg({x,y}, TSML))
        pp_sizes[sz] += 1
print(f"   Principal 2-plane size distribution: {dict(pp_sizes)}")
print(f"   Vidinli analog: every 2-plane = ℂ (2-dim) → TSML has {pp_sizes[2]} 2-dim 2-planes")

# ============================================================
# 5. MOUFANG / BOL / FLEXIBLE STRUCTURE
# ============================================================
print("\n5. MOUFANG / BOL / FLEXIBLE identity satisfaction")
total = N**3

# Flexible: x(yx) = (xy)x — comm satisfies trivially
flex = sum(1 for x in range(N) for y in range(N) 
           if TSML[x][TSML[y][x]] == TSML[TSML[x][y]][x])
print(f"   Flexible x(yx)=(xy)x: {flex}/{N**2}")

# Middle Moufang: (xy)(zx) = x((yz)x)
mid = sum(1 for x in range(N) for y in range(N) for z in range(N)
          if TSML[TSML[x][y]][TSML[z][x]] == TSML[x][TSML[TSML[y][z]][x]])
print(f"   Middle Moufang (xy)(zx)=x((yz)x): {mid}/{total}")

# Right Moufang: ((xy)z)y = x(y(zy))
rt = sum(1 for x in range(N) for y in range(N) for z in range(N)
         if TSML[TSML[TSML[x][y]][z]][y] == TSML[x][TSML[y][TSML[z][y]]])
print(f"   Right Moufang ((xy)z)y=x(y(zy)): {rt}/{total}")

# Left Bol: x(y(xz)) = (x(yx))z
lbol = sum(1 for x in range(N) for y in range(N) for z in range(N)
           if TSML[x][TSML[y][TSML[x][z]]] == TSML[TSML[x][TSML[y][x]]][z])
print(f"   Left Bol x(y(xz))=(x(yx))z: {lbol}/{total}")

# Jordan: x²(xy) = x(x²y)
jord = sum(1 for x in range(N) for y in range(N)
           if TSML[TSML[x][x]][TSML[x][y]] == TSML[x][TSML[TSML[x][x]][y]])
print(f"   Jordan x²(xy)=x(x²y): {jord}/{N**2}")

# ============================================================
# 6. NORM FORM — Vidinli/octonion have quadratic forms
# ============================================================
print("\n6. NORM FORM ANALOG")
print("   Octonion: N(x) = x·x̄, multiplicative: N(xy) = N(x)N(y)")
print("   TSML candidate: N(x) = TSML[x][x] (since TSML commutative, x̄ = x)")
print()
print(f"   {'x':>3s} {'N(x)=x²':>8s}")
for x in range(N): print(f"   {x:>3d} {TSML[x][x]:>8d}")

# Is this "norm" multiplicative?
nonmult = []
for x in range(N):
    for y in range(N):
        N_x = TSML[x][x]
        N_y = TSML[y][y]
        xy = TSML[x][y]
        N_xy = TSML[xy][xy]
        # Does N_xy relate to N_x and N_y in any consistent way?
        nonmult.append((x, y, N_x, N_y, N_xy))

# Check: N(xy) appears as HARMONY for which (x,y)?
harm_norm = sum(1 for (x,y,nx,ny,nxy) in nonmult if nxy == 7)
print(f"   N(xy) = HARMONY in {harm_norm}/{N**2} pairs (the 'absorbed' pairs)")

# Split: which pairs have N(xy) = 0 (void)?
void_norm = sum(1 for (x,y,nx,ny,nxy) in nonmult if nxy == 0)
print(f"   N(xy) = VOID in {void_norm}/{N**2} pairs")

# ============================================================
# 7. TRACE FORM
# ============================================================
print("\n7. TRACE ANALOG: T(x) = x + x̄ = 2x (for commutative).")
print("   But in mod-10 magma, 'trace' is ambiguous. Use: does x have image in axis?")
print("   Well-defined trace-like: does x appear anywhere in the table?")
print()
appearances = Counter()
for x in range(N):
    for y in range(N):
        appearances[TSML[x][y]] += 1
print(f"   How often each element appears in TSML:")
for v in range(N):
    print(f"     value {v}: {appearances[v]:>3d} cells")

# ============================================================
# 8. ALTERNATING GROUP STRUCTURE / DERIVATIONS
# ============================================================
print("\n8. AUTOMORPHISMS AND DERIVATIONS")
def is_aut(perm, T):
    for i in range(N):
        for j in range(N):
            if perm[T[i][j]] != T[perm[i]][perm[j]]: return False
    return True

# All automorphisms fixing 0 and 7
auts = []
for p in permutations(range(N)):
    if p[0]==0 and p[7]==7 and is_aut(p, TSML):
        auts.append(p)
print(f"   |Aut(TSML) fixing 0 and 7| = {len(auts)}")
# Describe
for a in auts:
    moved = [(i, a[i]) for i in range(N) if a[i] != i]
    if not moved: print(f"     identity")
    else: print(f"     moves: {moved}")

# ============================================================
# 9. SPECTRAL INVARIANTS
# ============================================================
print("\n9. SPECTRAL INVARIANTS (matrix view)")
M = np.array(TSML, dtype=float)
eigs = np.linalg.eigvals(M)
print(f"   Eigenvalues (sorted): {sorted(eigs.real, reverse=True)}")
print(f"   Rank: {np.linalg.matrix_rank(M)}")
print(f"   Determinant: {int(round(np.linalg.det(M)))}")
print(f"   Trace: {int(M.trace())}")
print(f"   Frobenius norm²: {float(np.sum(M**2)):.0f}")

# Vidinli: trace of multiplication operator L_x is 0 for pure imaginary (no real part)
# TSML analog: trace of row-x is sum of TSML[x][*]
print(f"\n   L_x trace (sum of row x): analog of Vidinli's trace-form")
for x in range(N):
    row_sum = sum(TSML[x])
    print(f"     x={x}: Σ TSML[x][*] = {row_sum}")

# ============================================================
# 10. QUADRATIC FORM / QUADRATIC REPRESENTATION
# ============================================================
print("\n10. QUADRATIC REPRESENTATION (Jordan algebra concept)")
print("    Jordan algebra has U_x : y ↦ 2x(xy) - x²y")
print("    For TSML commutative Jordan: U_x(y) = 2·TSML[x][TSML[x][y]] - TSML[TSML[x][x]][y] mod 10")
print()
print(f"    U_x(y) table (mod 10):")
print("    " + " ".join(f"{y:>3d}" for y in range(N)))
for x in range(N):
    row = []
    for y in range(N):
        U = (2 * TSML[x][TSML[x][y]] - TSML[TSML[x][x]][y]) % N
        row.append(U)
    print(f"  x={x}: " + " ".join(f"{v:>3d}" for v in row))

