"""
MANTERO BRIDGE: Treat the CL table as defining a QUADRATIC ALGEBRA.

The 10×10 CL table gives quadratic relations:
  x_i * x_j = x_{CL[i][j]}

Consider the quotient algebra:
  A = k[x_0, ..., x_9] / I
  I = ideal generated by (x_i x_j - x_{CL[i][j]}) for all i, j ∈ {0..9}

This puts TIG squarely in Mantero's research framework:
- Quadratic generators → Mantero's 4-quadric work
- Projective dimension analysis → his Stillman-conjecture work  
- Koszul property → his recent structural theorems
- Hilbert functions → his expertise

Compute:
  1. Number of independent quadratic relations (minus trivial duplicates)
  2. Hilbert function of A in low degrees
  3. Check basic Koszul conditions
"""
import numpy as np
from collections import Counter
from itertools import product

CL = [[0,0,0,0,0,0,0,7,0,0],[0,7,3,7,7,7,7,7,7,7],[0,3,7,7,4,7,7,7,7,9],
      [0,7,7,7,7,7,7,7,7,3],[0,7,4,7,7,7,7,7,8,7],[0,7,7,7,7,7,7,7,7,7],
      [0,7,7,7,7,7,7,7,7,7],[7,7,7,7,7,7,7,7,7,7],[0,7,7,7,8,7,7,7,7,7],
      [0,7,9,3,7,7,7,7,7,7]]
OP = ['VOID','LATTICE','COUNTER','PROGRESS','COLLAPSE',
      'BALANCE','CHAOS','HARMONY','BREATH','RESET']

# ─────────────────────────────────────────────────
# Task 1: Count independent quadratic relations
# ─────────────────────────────────────────────────
# A quadratic relation is  x_i x_j - x_{CL[i][j]} = 0 in degree 2
# In degree 2, the monomial basis of k[x_0..x_9] has C(11,2) = 55 monomials
# (since x_i x_j = x_j x_i commutative)
#
# Each relation x_i x_j - x_k maps monomial x_i x_j to linear combination
# but we also want to think of x_{CL[i][j]} as a degree-1 element (linear)
# — so these relations are NOT pure quadratic — they mix degrees!
#
# Instead: lift to GRADED setting. Use 10 GENERATORS of degree 1,
# consider in degree 2 the quadratic part:
#   x_i x_j  — a degree-2 monomial (commutative)
# and impose: x_i x_j = x_{CL[i][j]} * (something of degree 1)
# 
# This gets complicated. Let's use a simpler formulation:
#
# Take 10 generators x_0..x_9, each of degree 1.
# Identify x_i x_j with x_{CL[i][j]} x_0 (with x_0 as auxiliary generator).
# That gives quadratic relations: x_i x_j - x_{CL[i][j]} x_0 = 0
# ─────────────────────────────────────────────────

# Build the quadratic relations matrix
# Monomials in degree 2 over 10 variables: C(11, 2) = 55
# Basis: (x_i x_j) for 0 <= i <= j <= 9
monomials_deg2 = [(i, j) for i in range(10) for j in range(i, 10)]
N = len(monomials_deg2)
print(f"Number of degree-2 monomials in k[x_0..x_9]: {N}")
mono_idx = {m: k for k, m in enumerate(monomials_deg2)}

# Relations: x_i x_j - x_{CL[i][j]} * x_0
# In vector form: +1 at (i, j), -1 at (min(CL[i][j], 0), max(CL[i][j], 0))
relations = []
for i in range(10):
    for j in range(i, 10):
        target_k = CL[i][j]
        vec = np.zeros(N)
        vec[mono_idx[(min(i,j), max(i,j))]] += 1
        # target x_{target_k} * x_0 → monomial x_{min(0,k)} x_{max(0,k)}
        t = (min(0, target_k), max(0, target_k))
        vec[mono_idx[t]] -= 1
        # This will create a relation unless i == j and one monomial is zero
        if np.any(np.abs(vec) > 0):
            relations.append(vec)

R = np.array(relations)
print(f"Raw relations formed: {R.shape[0]}")
rank = np.linalg.matrix_rank(R)
print(f"Independent quadratic relations: rank = {rank}")
print(f"Algebra dimension in degree 2 = {N} - {rank} = {N - rank}")

# ─────────────────────────────────────────────────
# Task 2: Hilbert function in low degrees (simulation)
# ─────────────────────────────────────────────────
# Since the CL table is a commutative operation with HARMONY(7) as attractor,
# most products collapse to HARMONY or VOID. The algebra "sees" very few 
# distinct monomials.

# In fact, because CL is total (always defined), the algebra actually
# reduces degree-n monomials to degree-1 monomials after enough compositions.
# This is a RANK-1 Hilbert function if we identify x_i x_j = x_{CL[i][j]}.

# Let's compute: if x_i x_j ≡ x_{CL[i][j]} (identify degrees),
# then the "algebra" has only 10 distinct elements
# But as graded structure, we need to keep track of degree.

# Compute "reachable" set via compositions from each starting op
def fuse_chain(start, length):
    """Compose 'start' with random ops 'length' times."""
    state = start
    # Actually: all possible compositions give what fruit distribution?
    return state

# Compute fruit distribution for all n-tuples of operators at degree n
def all_fuse_n(n):
    """All possible CL-folds of n-tuples of operators, and their fruits."""
    if n == 1:
        return {op: 1 for op in range(10)}
    c = Counter()
    for tup in product(range(10), repeat=n):
        s = tup[0]
        for o in tup[1:]:
            s = CL[s][o]
        c[s] += 1
    return c

print()
print("="*70)
print("Hilbert-like: distribution of fruits from length-n CL folds")
print("="*70)
print(f"  {'n':>2s}  {'total':>8s}  " + "  ".join(f"{OP[o][:3]:>4s}" for o in range(10)))
for n in range(1, 6):
    c = all_fuse_n(n)
    total = 10**n
    print(f"  {n:>2d}  {total:>8d}  " + "  ".join(f"{c.get(o, 0):>4d}" for o in range(10)))

# ─────────────────────────────────────────────────
# Task 3: Star configuration angle
# ─────────────────────────────────────────────────
# A star configuration of s linear forms L_1..L_s in k[x_0..x_n] 
# is the ideal generated by products of the L_i's in specific patterns.
#
# TIG has 10 "operator elements". If we view these as 10 linear forms 
# in k[x_0..x_9], the DIAGONAL identifies operators with coordinate axes.
# 
# The star configuration structure would say:
# V(x_i x_j) where (i, j) runs over "special" pairs
# 
# TIG's bumps (off-HARMONY, off-VOID cells) — where are they?
bumps = []
for i in range(10):
    for j in range(i, 10):
        val = CL[i][j]
        if val not in (0, 7):
            bumps.append((i, j, val))
print(f"\n{len(bumps)} bump cells (not 0 or 7):")
for (i, j, v) in bumps:
    print(f"  x_{i} · x_{j} = x_{v}  ({OP[i]} · {OP[j]} = {OP[v]})")

# ─────────────────────────────────────────────────
# Task 4: Is the "HARMONY ideal" a linkage phenomenon?  
# Consider I = ideal of cells where CL[i][j] = HARMONY
# Consider J = ideal of cells where CL[i][j] = VOID
# Are these "linked" in Mantero's sense?
# ─────────────────────────────────────────────────
harmony_cells = [(i, j) for i in range(10) for j in range(i, 10) if CL[i][j] == 7]
void_cells = [(i, j) for i in range(10) for j in range(i, 10) if CL[i][j] == 0]
bump_cells = [(i, j) for i in range(10) for j in range(i, 10) if CL[i][j] not in (0, 7)]

print(f"\n{len(harmony_cells)} cells produce HARMONY(7)  — this is the large ideal 'I_H'")
print(f"{len(void_cells)} cells produce VOID(0)         — this is the ideal 'I_V'")
print(f"{len(bump_cells)} cells produce BUMPS            — exceptional set")
print(f"Total: {len(harmony_cells)+len(void_cells)+len(bump_cells)} = {55} ✓")

# Check: do harmony and void cells form a complete intersection?
# A CI in P^9 is a set cut out by codim-many equations.
# In our context, if H ∪ V cuts out a specific variety, it might be a CI.

# ─────────────────────────────────────────────────
# Task 5: The 10 operators as 10 points in P^9
# ─────────────────────────────────────────────────
# Each operator is a "coordinate point" [0:...:1:...:0] in P^9
# The CL relations define a variety V(I) ⊂ P^9 × P^9 × P^9
# Think of it as a HYPERGRAPH ideal (Mantero's area!)
print(f"\n" + "="*70)
print("HYPERGRAPH VIEW (Mantero's 2016-2017 work)")
print("="*70)
# Hypergraph: vertices {0..9}, edges are the 'composition triples' (i, j, CL[i][j])
edges = set()
for i in range(10):
    for j in range(10):
        edges.add(frozenset([i, j, CL[i][j]]))
print(f"Distinct composition triples (i, j, CL[i][j]) as hyperedges: {len(edges)}")
print(f"(For comparison: C(10,3) = 120 possible 3-vertex hyperedges)")
print(f"Density: {len(edges) / 120:.2%}")

# Size distribution
size_dist = Counter(len(e) for e in edges)
print(f"Edge size distribution: {dict(size_dist)}")
print(f"  Size 3 = all distinct, size 2 = one repeat (idempotent-like), size 1 = full idempotent")
