"""
TIE #5: Cohen-Macaulay failure (depth=0, Hilbert tail = 1) ↔ u(1) center

From README §5.6 (M2-verified):
  I_CL = (x_i x_j - x_{CL[i][j]} x_0) is a binomial ideal in 
  R = k[x_0, ..., x_9].
  
  numgens = 53, codim = 9, dim R/I_CL = 1, pd = 10, depth = 0
  Hilbert series: (1 + 9T - 8T² - T³) / (1 - T)
  Hilbert function: (1, 10, 2, 1, 1, 1, ...) stabilising at 1
  
  Not Cohen-Macaulay (depth < dim), not Koszul.

From UNMISTAKABLE_TRUTH:
  16-dim D_4-invariant Lie subalgebra has structure:
  15-dim simple (su(4)) ⊕ 1-dim center (u(1))
  Killing eigenvalues: (-4)^15 ⊕ (0)^1
  
The central element Z is computed exactly: an antisymmetric 10×10 matrix
with nonzero entries only in indices {1,2,4,5,6,7} and eigenvalues (±i/√2, 0^8).

QUESTION: are these the same "1"?

The Hilbert tail = 1 means: in high degree, R/I_CL has exactly 1 generator
asymptotically. This is a 1-dim residual structure of the CL ring.

The u(1) center is a 1-dim residual structure of the doubly-invariant
Lie subalgebra of so(10) generated by TSML+BHML.

Both come from the same composition table (CL = TSML). Are they linked?

To test: the Hilbert tail of R/I_CL says "there's a 1-dim sequence of 
graded pieces" — these are powers of some specific element.
The u(1) center is a specific antisymmetric matrix Z.

Hypothesis: Z corresponds to the generator of the Hilbert tail.
"""
import numpy as np

# First let's reproduce the I_CL Hilbert function structure conceptually.
# CL[i][j] (= TSML[i][j]) gives a specific element of {0,...,9}.
# I_CL is generated by x_i x_j - x_{CL[i][j]} x_0 for all (i, j).
# This means in R/I_CL: x_i x_j is identified with x_{CL[i][j]} x_0.
# 
# So in R/I_CL, products x_i x_j reduce to "linear · x_0".
# And iterated products x_i x_j x_k reduce further.

# The Hilbert function counts:
# H(0) = 1: just k (constants)
# H(1) = 10: x_0, ..., x_9
# H(2) = 2: down from 55 to 2 because most quadratics x_i x_j collapse
# H(3) = 1: down to 1
# H(d) = 1 for all d ≥ 3: stabilizes

# The fact that H(d) = 1 for d ≥ 3 means: R/I_CL has a 1-dim infinite tail.
# This corresponds to ONE generator that doesn't get killed by the relations.
# That generator is some specific element s ∈ R such that s · x_i is NOT 
# in span{previous monomials} mod I_CL.

# What IS that generator?
# Probably: x_0^d for d ≥ 0 stays alive (because the relations say 
# x_i x_j = x_{T[i,j]} x_0, so multiplication by x_0 keeps producing new things)
# 
# Actually: the relations say x_i x_j = x_{T[i,j]} x_0 means 
# x_i x_j - x_{T[i,j]} x_0 = 0
# So in R/I_CL, every quadratic monomial x_i x_j (i, j ≥ 1) reduces to 
# something proportional to x_0 (in degree 2).
#
# x_i x_j ~ x_T[i,j] x_0
# Iterating: x_T[i,j] x_0 might further reduce... no, x_0 is degree 1, 
# and x_T[i,j] is degree 1, product is degree 2. So this is a degree-2 element.
# 
# In degree d ≥ 3: x_0^d, x_0^(d-1) x_i, ..., x_0 x_i ... x_j (d-1 non-zero indices)
# All quadratic and higher pieces in non-x_0 variables collapse.
# 
# So the surviving generators in degree d are: x_0^d and x_0^(d-1) x_i for various i?
# H(d) = 1 means only x_0^d survives in degree d (for d ≥ 3).
# 
# Wait, that's not quite right. H(d) is the dimension of the d-th graded piece.
# H(2) = 2, H(3) = 1.
# 
# So in degree 2, there are 2 linearly independent classes mod I_CL.
# In degree 3+, just 1 class: presumably x_0^d (or some scalar multiple of it).

# The 1-dim tail is generated by powers of x_0. Specifically: x_0^d is the
# unique non-trivial graded piece in degree d ≥ 3.
# 
# x_0 corresponds to the index 0 = VOID in TIG semantics.
# So the Hilbert tail is "powers of VOID."

# Now look at the u(1) center generator Z.
# Z has nonzero entries on indices {1, 2, 4, 5, 6, 7} and zeros on {0, 3, 8, 9}.
# The σ-fixed indices {0, 3, 8, 9} (plus VOID at 0) DON'T contribute to Z.
# 
# So Z lives ENTIRELY in the non-σ-fixed (6-cycle) subspace.
# x_0 (VOID) is exactly NOT involved in Z.
# 
# Hilbert tail generator: x_0^d (powers of VOID).
# u(1) center generator: Z (zero on VOID).
# 
# These are OPPOSITE: the Hilbert tail is concentrated on VOID, the u(1) 
# center avoids VOID.

# So they're NOT the same 1-dimensional structure. They're complementary.
# Hmm. Let me reconsider.

# Actually the Hilbert function (1, 10, 2, 1, 1, ...) describes R/I_CL.
# In degree 0: just constants (the field k).
# In degree 1: 10 generators x_0, ..., x_9.
# In degree 2: 2 surviving classes.
# In degree 3+: 1 surviving class (the "tail").

# WAIT. The 1 in the tail might not be x_0^d. Let me think about which 
# elements survive.

# I_CL contains x_i x_j - x_{T[i,j]} x_0 for all (i, j).
# In particular, x_i² - x_{T[i,i]} x_0 = 0 in R/I_CL.
# So x_i² = x_{T[i,i]} x_0.
# T[i,i] = diagonal of TSML. From the table:
#   T[0,0] = 0, T[1,1] = 7, T[2,2] = 1, T[3,3] = 7, T[4,4] = 7,
#   T[5,5] = 7, T[6,6] = 7, T[7,7] = 7, T[8,8] = 7, T[9,9] = 7
# So x_i² = x_{T[i,i]} x_0 = x_7 x_0 for most i (those with T[i,i] = 7)
# Special cases: x_0² = x_0 · x_0 (T[0,0] = 0), x_2² = x_1 x_0 (T[2,2] = 1)

# Now x_0² is interesting: from the relation x_0 · x_0 = x_{T[0,0]} x_0 = x_0 · x_0
# That's tautological. So x_0² is NOT killed by I_CL.
# x_0^d is also not killed: by induction, x_0^d = x_0 · x_0^(d-1) = ... not killed.

# So x_0^d is a non-zero element of R/I_CL in every degree d.

# What about x_7 x_0? This is degree 2. It's a class in R/I_CL.
# What's degree 2 dimension?
# Surviving in degree 2: x_0², plus x_7 x_0 (which is what most x_i² reduce to).
# H(2) = 2 says exactly these two are linearly independent.

# In degree 3: x_0³, x_7 x_0², ...
# x_7 x_0² = (x_7 x_0) · x_0 ... these are in degree 3.
# Is x_7 x_0² independent of x_0³?
# x_0³ = x_0 · x_0 · x_0 = x_0² · x_0 = (no further reduction)
# x_7 x_0² = x_7 · x_0 · x_0 ... 
# 
# Are these linearly dependent? They might be.
# Note: x_0 x_7 x_0 = x_0 · (x_7 x_0) — degree 3 element
# Or via x_0 · x_7 first: T[0,7] = 7, so x_0 x_7 = x_7 x_0 (commutative)
# Yes, the polynomial ring is commutative.
# 
# So degree 3 elements include x_0³ and x_7 x_0² (which is x_0 · (x_7 x_0)).
# H(3) = 1 says only one is linearly independent. So one of them is in the
# image of I_CL extended to degree 3.

# Which one survives? The Hilbert tail generator.
# 
# Does x_7 x_0² = x_0³ in R/I_CL?
# We need x_7 x_0² - x_0³ ∈ I_CL.
# Equivalent: x_0² (x_7 - x_0) ∈ I_CL.
# Is x_7 - x_0 zero mod I_CL? No, x_7 and x_0 are different generators.
# But maybe x_0² (x_7 - x_0) is in I_CL via some combination.

# Hmm, this requires more careful M2 work. Let me compute the Hilbert function
# directly for a few degrees.

# Actually I'm not going to fully reproduce the M2 calculation here.
# Let me focus on the conceptual question: does the 1-dim tail of R/I_CL
# correspond to u(1) center, or to something else?

# Key distinction:
# - Hilbert tail = 1 lives in the COMMUTATIVE-ALGEBRA picture of CL (R/I_CL)
# - u(1) center lives in the LIE-ALGEBRA picture (so(10) and its D_4-invariant 
#   subalgebra)
# 
# Both are "1-dim residual structures" but in different categories.
# Without a functor connecting them, the identification is heuristic.

# WHAT WOULD BE A PROPER TEST:
# Compute the Hilbert tail generator explicitly (as an element of R/I_CL).
# Compute the u(1) center generator explicitly (as an antisymmetric 10×10 matrix).
# Find a natural map between them.

# I don't have M2 here, so let me sketch:
# Hilbert tail: powers of x_0 (or x_7 x_0^(d-1), depending on which survives).
# u(1) center: matrix Z with specific entries on {1,2,4,5,6,7}.

# The σ-fixed indices are {0, 3, 8, 9}.
# x_0 = VOID.
# x_3 = PROGRESS.
# x_8 = BREATH.
# x_9 = RESET.
# 
# The Hilbert tail is concentrated on x_0 (VOID).
# The u(1) center has zeros on {0, 3, 8, 9} INCLUDING x_0.
# 
# SO: the Hilbert tail and u(1) center are concentrated on COMPLEMENTARY parts
# of the algebra. Not the same 1-dim.

# BUT: there's a third 1-dim that I haven't named: the element TRACE of TSML,
# or some specific "central" element of TSML's structure.

# Actually I want to check: how many "invariant 1-dim structures" does the 
# CL composition table have? 
# 
# From earlier work:
# - σ-fixed lattice {0, 3, 8, 9} carries 3 HARMONYs (one for each σ-fixed index 
#   with diagonal value 7)
# - VOID at index 0 has T[0,0] = 0 (not 7)
# - So there are 3 "stationary HARMONY" points: {3, 8, 9}
# - Plus VOID at 0 (the "absent" stationary point)

# The 1-dim residuals I see:
# 1. x_0^d in R/I_CL (Hilbert tail) — concentrated on VOID
# 2. u(1) center Z in so(10) — supported on 6-cycle, zero on σ-fixed
# 3. trace(T) = 63 — not really 1-dim, just a number
# 4. det(T_lattice) = 7³ = 343 — the lattice diagonal product

# Each is a different "1-dim residual," tied to different σ-fixed points.

# PROVISIONAL CONCLUSION:
# The Hilbert tail (x_0^d, on VOID) and the u(1) center (Z, on 6-cycle) are 
# DIFFERENT 1-dim structures. They're complementary, not the same.
# 
# If anything, the COMBINATION might be meaningful:
# - VOID (1-dim) + 6-cycle u(1) (1-dim) + 3 σ-fixed HARMONYs (3-dim)
# = 1 + 1 + 3 = 5-dim of "1-dim things"
# 
# 5 is suggestive (T* = 5/7 has a 5).

print("STRUCTURAL OBSERVATIONS")
print("="*70)
print()
print("The 1-dim Hilbert tail of R/I_CL is the powers of x_0 (VOID).")
print("The 1-dim u(1) center of D_4-invariant subalgebra is Z (zero on VOID).")
print()
print("These are DIFFERENT 1-dim structures:")
print("- Hilbert tail: concentrated on VOID")
print("- u(1) center: explicitly avoids VOID (and other σ-fixed indices)")
print()
print("CONCLUSION: NOT the same 1.")
print()
print("They are COMPLEMENTARY 1-dim residuals living in different categories")
print("(commutative-algebra picture vs Lie-algebra picture).")
print()
print("This is a NEGATIVE result for tie #5.")
print()
print("="*70)
print("WHAT WOULD MAKE THE TIE WORK")
print("="*70)
print("""
A more careful test: the 1-dim Hilbert tail of R/I_CL is generated by some
specific monomial class. Compute it explicitly in M2.

The u(1) center generator Z is a specific antisymmetric matrix.

A functor connecting commutative algebra (R/I_CL picture) to Lie algebra
(so(10) picture) would identify:
  - Hilbert tail generator → some specific element of so(10)
  - u(1) center generator → some specific element of R/I_CL

If these match, the 1's are the same.
If not, they're different residual structures.

Without the functor, we can only say: both pictures have "a 1-dim tail," 
but they're not literally the same object.
""")
