/*
 * i2s_receiver.v -- I2S Slave Receiver for MEMS Microphone
 * ==========================================================
 * Operator: COUNTER (2) -- CK measures the world.
 *
 * Receives I2S audio from an INMP441 or similar MEMS mic.
 * Captures 24-bit PCM samples at 48kHz, writes to a FIFO
 * that the ARM reads via AXI.
 *
 * I2S protocol (from mic's perspective):
 *   - SCK (bit clock): generated by FPGA, typ. 48kHz * 64 = 3.072 MHz
 *   - WS  (word select): generated by FPGA, toggles every 32 SCK cycles
 *     WS=0 = left channel, WS=1 = right channel
 *   - SD  (serial data): from mic, MSB first, 24-bit in 32-bit frame
 *     Data valid on rising edge of SCK (INMP441)
 *
 * INMP441 specifics:
 *   - L/R pin selects channel: LOW = left (WS low), HIGH = right (WS high)
 *   - Data output: 24-bit, MSB first, left-justified in 32-bit frame
 *   - 1 SCK cycle delay after WS transition before first data bit
 *
 * Target: Zynq-7020 Artix-7 fabric, 100 MHz system clock.
 *
 * (c) 2026 Brayden Sanders / 7Site LLC -- TIG Unified Theory
 */

module i2s_receiver #(
    parameter CLK_FREQ    = 100_000_000,  // System clock (100 MHz)
    parameter SAMPLE_RATE = 48000,        // Audio sample rate
    parameter FIFO_DEPTH  = 256           // Sample FIFO depth
)(
    input  wire        clk,
    input  wire        rst_n,

    // I2S pins (directly to INMP441 MEMS mic)
    output reg         i2s_sck,         // Bit clock (3.072 MHz for 48kHz)
    output reg         i2s_ws,          // Word select (left/right)
    input  wire        i2s_sd,          // Serial data from mic

    // AXI-side interface (ARM reads samples here)
    output wire [23:0] sample_out,      // 24-bit PCM sample (signed)
    output wire        sample_valid,    // Pulse when new sample ready
    input  wire        sample_read,     // ARM acknowledges read
    output wire        fifo_empty,
    output wire [7:0]  fifo_count
);

    // -- I2S Clock Generation --
    // SCK = SAMPLE_RATE * 64 (32 bits per channel * 2 channels)
    // For 48kHz: SCK = 3.072 MHz
    // Divider: 100 MHz / 3.072 MHz / 2 = ~16 (half-periods)
    localparam SCK_FREQ = SAMPLE_RATE * 64;
    localparam SCK_DIV  = CLK_FREQ / SCK_FREQ / 2;

    reg [$clog2(SCK_DIV)-1:0] sck_cnt;
    reg sck_toggle;  // Pulses at 2x SCK rate

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            sck_cnt <= 0;
            sck_toggle <= 0;
            i2s_sck <= 0;
        end else begin
            if (sck_cnt >= SCK_DIV - 1) begin
                sck_cnt <= 0;
                sck_toggle <= 1;
                i2s_sck <= ~i2s_sck;
            end else begin
                sck_cnt <= sck_cnt + 1;
                sck_toggle <= 0;
            end
        end
    end

    // -- I2S Bit Counter + Word Select --
    reg [5:0] bit_cnt;  // 0-63 (32 bits * 2 channels)
    reg [31:0] shift_reg;
    reg [23:0] captured_sample;
    reg capture_valid;

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            bit_cnt <= 0;
            i2s_ws <= 0;
            shift_reg <= 0;
            captured_sample <= 0;
            capture_valid <= 0;
        end else if (sck_toggle && i2s_sck) begin
            // Rising edge of SCK: shift in data, advance counter
            capture_valid <= 0;

            // Shift in serial data (MSB first)
            shift_reg <= {shift_reg[30:0], i2s_sd};
            bit_cnt <= bit_cnt + 1;

            // At bit 32: left channel complete, capture sample
            if (bit_cnt == 31) begin
                // WS was 0 (left channel) for bits 0-31
                // Extract 24 MSBs (INMP441 outputs 24-bit left-justified)
                captured_sample <= shift_reg[30:7]; // Bits [31:8] after final shift
                capture_valid <= 1;
                i2s_ws <= 1; // Switch to right channel
            end

            // At bit 63: right channel complete, back to left
            if (bit_cnt == 63) begin
                bit_cnt <= 0;
                i2s_ws <= 0; // Back to left channel
                // We only capture left channel (mono mic)
            end
        end else begin
            capture_valid <= 0;
        end
    end

    // -- Sample FIFO --
    reg [23:0] fifo_mem [0:FIFO_DEPTH-1];
    reg [$clog2(FIFO_DEPTH)-1:0] fifo_wr_ptr;
    reg [$clog2(FIFO_DEPTH)-1:0] fifo_rd_ptr;
    reg [$clog2(FIFO_DEPTH):0]   fifo_level;

    assign fifo_empty = (fifo_level == 0);
    assign fifo_count = fifo_level[$clog2(FIFO_DEPTH):0];
    assign sample_out = fifo_mem[fifo_rd_ptr];
    assign sample_valid = !fifo_empty;

    // FIFO write (from I2S capture)
    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            fifo_wr_ptr <= 0;
            fifo_rd_ptr <= 0;
            fifo_level  <= 0;
        end else begin
            // Write
            if (capture_valid && fifo_level < FIFO_DEPTH) begin
                fifo_mem[fifo_wr_ptr] <= captured_sample;
                fifo_wr_ptr <= fifo_wr_ptr + 1;
            end

            // Read (ARM acknowledges)
            if (sample_read && !fifo_empty) begin
                fifo_rd_ptr <= fifo_rd_ptr + 1;
            end

            // Level tracking
            case ({capture_valid && fifo_level < FIFO_DEPTH,
                   sample_read && !fifo_empty})
                2'b10: fifo_level <= fifo_level + 1;
                2'b01: fifo_level <= fifo_level - 1;
                default: ;
            endcase
        end
    end

endmodule
