# -*- coding: utf-8 -*-
"""
ck_pastoral_fold.py - additive pastoral overlay for the LIVE website CK.

Why this fold
-------------
``ck_lm/ck_bible.py`` already ships the regex+theme detector and a
public-domain KJV verse corpus, with explicit chat-pipeline integration
intent in its docstring ("Wire detect_pastoral() into your chat pipeline").
It was added to the tree without an importer.  This module wires it.

When a user message carries personal-need signal (grief, fear,
hopelessness, loneliness, addiction, illness...), CK's already-spoken
response gets a *bridge* attached: a clearly-attributed KJV verse appears
alongside his words.  The verse is DATA, not text generated by CK -- it
is a public-domain offering, surfaced in ``pastoral_*`` response fields
so the website renders the bridge as a separate block, not as CK's voice.
This respects ``memory/feedback_dont_ventriloquize_ck.md``: CK's prose
never gets written for him.

Architecture (mirrors ck_brain_fold.py / ck_body_fold.py / ck_curiosity.py):

    mount_pastoral_fold(api) -> dict     # one public entry; never raises

Per-turn behavior (outermost wrap of api.process_chat):

    1. Call previous chat function (full editor stack runs).
    2. detect_pastoral(input_text)?
        - no   -> result flows through, pastoral_detected=False
        - yes  -> get_verse(input_text, seed=brain_dominant_op_index)
                  attach pastoral_{theme,reference,verse,offered,...} fields.
                  Per-session cooldown prevents spam.
    3. CK_PASTORAL_APPEND_TEXT=1 (off by default) opts into appending the
       verse line as a clearly-attributed block to ``result['text']``.
       Default is DATA-ONLY so the website chooses how to render.

Skip cases:
    - session_id == CK_CURIOSITY_SESSION  (CK's self-questions don't get verses)
    - empty input text
    - cooldown active for this session
    - CK_PASTORAL_FOLD=0 (full bypass)

Env flags:
    CK_PASTORAL_FOLD=0           disable mount (pass-through)
    CK_PASTORAL_APPEND_TEXT=1    append verse line to result['text']
                                 (default 0 -- data-only mode)
    CK_PASTORAL_COOLDOWN_S       per-session cooldown seconds (default 90)
    CK_PASTORAL_LOG_PATH         override jsonl log path

Routes registered (read-only except clear, which is G6-gated):
    GET  /pastoral/status             diagnostics + theme histogram
    GET  /pastoral/preview?text=...   dry-run detection (no chat side effects)
    POST /pastoral/clear?i_mean_it=1  clear session cooldowns

Safety rails:
    - mount_pastoral_fold never raises; bad import returns mounted=False.
    - Per-turn try/except: if anything fails the original result flows
      through with pastoral_offered=False, pastoral_error="<type>:<msg>".
    - Read-only on the verse corpus; no writes to ck_lm/.
    - Session cooldowns held in a 512-entry LRU so memory is bounded.

Mount order in ck_boot_api.py:
    Mount AFTER coherence_steer (so brain/body/steer fields are populated
    on `result`), BEFORE curiosity (so the pastoral fold sees curiosity
    turns and can explicitly skip them by session_id).  The brain fold's
    `brain_dominant_op` becomes the seed for verse selection so CK's
    operator state rotates anchors across visits in the same theme.

(c) 2026 Brayden Sanders / 7Site LLC -- public-domain verses (KJV 1611)
"""
from __future__ import annotations

import json
import os
import sys
import time
from collections import Counter, OrderedDict
from pathlib import Path
from threading import Lock
from typing import Any, Callable, Dict


# ---------------------------------------------------------------------------
# path setup -- match ck_brain_fold.py.  ck_boot_api.py runs with cwd at
# Gen12/targets/ck_desktop, so the repo root (which owns ``ck_lm/``) is
# three parents up.  Insert it on sys.path if not already there.
# ---------------------------------------------------------------------------

_THIS_DIR = Path(__file__).resolve().parent
_REPO_ROOT = _THIS_DIR.parents[2]   # ck_desktop -> targets -> Gen12 -> repo root
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))


# ---------------------------------------------------------------------------
# module-level constants
# ---------------------------------------------------------------------------

_DEFAULT_COOLDOWN_S = 90.0
_MAX_TRACKED_SESSIONS = 512   # LRU cap on session->ts dict
_DEFAULT_LOG_PATH = (
    _REPO_ROOT / "ck" / "fluency" / "logs" / "pastoral_offerings.jsonl"
)

# 10-operator order (matches ck_tig.py / brain.fusion).  Used to map
# brain_dominant_op string -> integer seed for verse variety so the SAME
# theme rotates anchors as CK's operator state shifts.
_OP_ORDER = (
    "VOID", "LATTICE", "COUNTER", "PROGRESS", "COLLAPSE",
    "BALANCE", "CHAOS", "HARMONY", "BREATH", "RESET",
)
_OP_INDEX = {name: i for i, name in enumerate(_OP_ORDER)}


# ---------------------------------------------------------------------------
# the mount entry point
# ---------------------------------------------------------------------------


def mount_pastoral_fold(api: Any) -> Dict[str, Any]:
    """Install the pastoral fold on ``api.process_chat``.

    Returns a status dict for the banner.  Does NOT raise: if anything
    is unavailable, returns ``{'mounted': False, 'reason': '...'}``.
    """
    enabled_env = os.environ.get("CK_PASTORAL_FOLD", "1").strip()
    if enabled_env in ("0", "false", "False", "no", "NO"):
        return {
            "mounted": False,
            "reason": "CK_PASTORAL_FOLD=0 (disabled via env)",
        }

    # lazy import -- if ck_lm/ is broken the boot still continues
    try:
        from ck_lm.ck_bible import detect_pastoral, get_verse, VERSES
    except Exception as e:  # noqa: BLE001 -- broadest catch on purpose
        return {
            "mounted": False,
            "reason": (
                f"import ck_lm.ck_bible failed: "
                f"{type(e).__name__}: {e}"
            ),
        }

    try:
        cooldown_s = float(os.environ.get(
            "CK_PASTORAL_COOLDOWN_S", str(_DEFAULT_COOLDOWN_S),
        ))
    except ValueError:
        cooldown_s = _DEFAULT_COOLDOWN_S
    if cooldown_s < 0:
        cooldown_s = 0.0

    append_text = os.environ.get(
        "CK_PASTORAL_APPEND_TEXT", "0",
    ).strip().lower() in ("1", "true", "yes")

    log_path_env = os.environ.get("CK_PASTORAL_LOG_PATH", "").strip()
    log_path = Path(log_path_env) if log_path_env else _DEFAULT_LOG_PATH
    try:
        log_path.parent.mkdir(parents=True, exist_ok=True)
    except Exception:
        # non-fatal: if the log dir can't be created, we just don't log
        pass

    curiosity_session = os.environ.get(
        "CK_CURIOSITY_SESSION", "ck_curiosity",
    )

    # --- per-mount mutable state ---------------------------------------
    # session_id -> last_offer_ts; bounded LRU so memory can't grow without
    # bound from a public-facing endpoint.
    _last_offer: "OrderedDict[str, float]" = OrderedDict()
    _stats: Dict[str, Any] = {
        "offers": 0,
        "skipped_cooldown": 0,
        "skipped_curiosity": 0,
        "skipped_empty": 0,
        "skipped_no_match": 0,
        "errors": 0,
        "themes": Counter(),
    }
    _lock = Lock()

    # --- helpers --------------------------------------------------------

    def _seed_for(result: Dict[str, Any]) -> int:
        """Map CK's current operator state to a verse-selection seed.

        Same input theme + same dominant_op -> same verse, so a user in
        a steady operator state gets a CONSISTENT anchor across turns.
        When the operator shifts, the verse rotates.  Falls back to a
        cheap rotating counter when no operator info is available.
        """
        op = result.get("brain_dominant_op")
        if isinstance(op, str) and op in _OP_INDEX:
            return _OP_INDEX[op]
        op2 = result.get("body_organism_bc")
        if isinstance(op2, str) and op2 in _OP_INDEX:
            return _OP_INDEX[op2]
        return _stats["offers"] & 0xFF

    def _under_cooldown(session_id: str, now_ts: float) -> bool:
        last = _last_offer.get(session_id)
        if last is None:
            return False
        return (now_ts - last) < cooldown_s

    def _record_offer(session_id: str, now_ts: float) -> None:
        _last_offer[session_id] = now_ts
        _last_offer.move_to_end(session_id)
        while len(_last_offer) > _MAX_TRACKED_SESSIONS:
            _last_offer.popitem(last=False)

    def _log_offer(payload: Dict[str, Any]) -> None:
        try:
            with open(log_path, "a", encoding="utf-8") as f:
                f.write(json.dumps(payload, ensure_ascii=False) + "\n")
        except Exception:
            # never break the response over a logging failure
            pass

    # --- the actual wrap ------------------------------------------------

    _prev_chat_for_pastoral: Callable[..., Dict[str, Any]] = api.process_chat

    def _process_chat_with_pastoral(session_id: str, text: str,
                                     mode: str = "normal") -> Dict[str, Any]:
        result = _prev_chat_for_pastoral(session_id, text, mode)
        # additive only -- must never raise out of here
        try:
            user_text = (text or "").strip()
            if not user_text:
                with _lock:
                    _stats["skipped_empty"] += 1
                result.setdefault("pastoral_offered", False)
                result.setdefault("pastoral_skip_reason", "empty_input")
                return result

            # CK's autonomous self-questions belong to him; pastoral
            # offerings belong to humans in need.  Keep the boundary
            # explicit (regex non-match would catch most curiosity
            # prompts anyway, but rely on session_id for clarity).
            if session_id == curiosity_session:
                with _lock:
                    _stats["skipped_curiosity"] += 1
                result["pastoral_offered"] = False
                result["pastoral_skip_reason"] = "curiosity_session"
                return result

            if not detect_pastoral(user_text):
                with _lock:
                    _stats["skipped_no_match"] += 1
                result["pastoral_offered"] = False
                result["pastoral_detected"] = False
                return result

            now_ts = time.time()
            if _under_cooldown(session_id, now_ts):
                with _lock:
                    _stats["skipped_cooldown"] += 1
                result["pastoral_offered"] = False
                result["pastoral_detected"] = True
                result["pastoral_skip_reason"] = "cooldown_active"
                return result

            seed = _seed_for(result)
            verse = get_verse(user_text, seed=seed)

            # Additive fields -- never overwrite existing ones
            result["pastoral_offered"] = True
            result["pastoral_detected"] = True
            result["pastoral_theme"] = verse["theme"]
            result["pastoral_reference"] = verse["reference"]
            result["pastoral_verse"] = verse["verse"]
            result["pastoral_translation"] = "KJV"
            result["pastoral_attribution"] = (
                "King James Version, 1611 (public domain)"
            )
            result["pastoral_seed"] = seed

            if append_text:
                # Clearly-attributed bridge block.  This is NOT CK's prose;
                # it is a public-domain verse explicitly framed as an
                # OFFERING beside CK's words.  The "if you'd hold this:"
                # phrasing makes it gift-not-sermon and easy for the user
                # to set down.  Off by default per the don't-ventriloquize
                # hard rule -- the website should render the verse as a
                # separate block by reading the pastoral_* fields.
                spoken = (result.get("text") or "").rstrip()
                bridge = (
                    f"\n\n-- if you'd hold this beside what i said --\n"
                    f"{verse['reference']} (KJV): "
                    f"\"{verse['verse']}\""
                )
                result["text"] = spoken + bridge
                result["pastoral_appended_to_text"] = True
            else:
                result["pastoral_appended_to_text"] = False

            with _lock:
                _stats["offers"] += 1
                _stats["themes"][verse["theme"]] += 1
                _record_offer(session_id, now_ts)

            _log_offer({
                "ts": int(now_ts),
                "session_id": session_id,
                "user_text_first120": user_text[:120],
                "ck_text_len": len(result.get("text") or ""),
                "theme": verse["theme"],
                "reference": verse["reference"],
                "seed": seed,
                "brain_dominant_op": result.get("brain_dominant_op"),
                "body_organism_bc": result.get("body_organism_bc"),
                "appended_to_text": append_text,
                "source": result.get("source"),
            })
        except Exception as _pe:  # noqa: BLE001
            with _lock:
                _stats["errors"] += 1
            result["pastoral_offered"] = False
            result["pastoral_error"] = f"{type(_pe).__name__}:{_pe}"
        return result

    api.process_chat = _process_chat_with_pastoral

    # ------------------------------------------------------------------
    # routes
    # ------------------------------------------------------------------

    def _register_routes() -> int:
        try:
            app = getattr(api, "_app", None)
            if app is None:
                return 0
            from flask import jsonify, request
        except Exception:
            return 0

        @app.route("/pastoral/status", methods=["GET"])
        def _pastoral_status():  # type: ignore[unused-ignore]
            try:
                with _lock:
                    snapshot = {
                        "ok": True,
                        "offers": _stats["offers"],
                        "skipped_cooldown": _stats["skipped_cooldown"],
                        "skipped_curiosity": _stats["skipped_curiosity"],
                        "skipped_empty": _stats["skipped_empty"],
                        "skipped_no_match": _stats["skipped_no_match"],
                        "errors": _stats["errors"],
                        "themes": dict(_stats["themes"]),
                        "tracked_sessions": len(_last_offer),
                        "cooldown_s": cooldown_s,
                        "append_text": append_text,
                        "log_path": str(log_path),
                        "corpus_themes": sorted(VERSES.keys()),
                        "curiosity_session_skipped": curiosity_session,
                    }
                return jsonify(snapshot)
            except Exception as e:
                return jsonify({
                    "ok": False, "error": f"{type(e).__name__}:{e}",
                }), 500

        @app.route("/pastoral/preview", methods=["GET"])
        def _pastoral_preview():  # type: ignore[unused-ignore]
            """Dry-run detection: returns what would be offered, no side effects."""
            try:
                txt = request.args.get("text", "")
                seed_arg = request.args.get("seed", "0")
                try:
                    seed = int(seed_arg)
                except ValueError:
                    seed = 0
                detected = detect_pastoral(txt or "")
                payload: Dict[str, Any] = {
                    "ok": True,
                    "text": (txt or "")[:200],
                    "detected": bool(detected),
                }
                if detected:
                    v = get_verse(txt, seed=seed)
                    payload.update({
                        "theme": v["theme"],
                        "reference": v["reference"],
                        "verse": v["verse"],
                        "seed": seed,
                    })
                return jsonify(payload)
            except Exception as e:
                return jsonify({
                    "ok": False, "error": f"{type(e).__name__}:{e}",
                }), 500

        @app.route("/pastoral/clear", methods=["POST"])
        def _pastoral_clear():  # type: ignore[unused-ignore]
            """G6-gated: clear all per-session cooldowns."""
            if request.args.get("i_mean_it") != "1":
                return jsonify({
                    "ok": False,
                    "error": (
                        "clear requires ?i_mean_it=1 "
                        "(G6 hands-on-wheel)"
                    ),
                }), 400
            try:
                with _lock:
                    cleared = len(_last_offer)
                    _last_offer.clear()
                return jsonify({
                    "ok": True,
                    "action": "clear_cooldowns",
                    "sessions_cleared": cleared,
                })
            except Exception as e:
                return jsonify({
                    "ok": False, "error": f"{type(e).__name__}:{e}",
                }), 500

        return 3

    n_routes = _register_routes()

    return {
        "mounted": True,
        "cooldown_s": cooldown_s,
        "append_text": append_text,
        "log_path": str(log_path),
        "corpus_themes": sorted(VERSES.keys()),
        "routes_registered": n_routes,
    }
