"""
D8: CL OPERATOR ENCODING — W=3/50 ENCODES ALL 10 OPERATORS ALGEBRAICALLY

Copyright © 2025–2026 Brayden Ross Sanders / 7SiTe LLC
Licensed under the 7SiTe Public Sovereignty License v1.0.
Human use only. No commercial use. No government use.
No military, intelligence, policing, or surveillance use.
See LICENSE for full terms. DOI: 10.5281/zenodo.18852047
Luther-Sanders Research Framework | April 1 2026

PROMOTES C18 → D8.

THEOREM D8 (CL Operator Encoding):
  Let W = 3/50. The carrier function sin²(πk/(2Wp)) evaluated over
  integer indices k generates zeros and maxima that trace EVERY operator
  in the CL alphabet {0..9} exactly once per period:

    ZEROS at t = 2nW:      operator(t) = (6n) mod 10
    Operators covered: {0, 2, 4, 6, 8} = EVEN = STRUCTURE class

    MAXIMA at t = (2n-1)W:  operator(t) = 3(2n-1) mod 10
    Operators covered: {1, 3, 5, 7, 9} = ODD = FLOW class

    UNION: EVEN ∪ ODD = Z/10Z = ALL 10 CL operators.

ALGEBRAIC PROOF (no computation):

  W = 3/50 = (CL generator 3) / (half table cells = 5 × 10)

  ZEROS SIDE — gcd(6, 10) = 2:
    Zeros at t = 2nW = 6n/50 → operator index = (6n) mod 10.
    The set {6n mod 10 : n ∈ Z} = <6> in Z/10Z.
    Since gcd(6, 10) = 2, the subgroup <6> = 2Z/10Z = {0, 2, 4, 6, 8}.
    This is the EVEN operator class: {VOID, DOING, COLLAPSE, ASCEND, BREATH}.
    Coverage: exactly 5 operators, all EVEN.

  MAXIMA SIDE — gcd(3, 10) = 1:
    Maxima at t = (2n-1)W = 3(2n-1)/50 → operator index = 3(2n-1) mod 10.
    The values 2n-1 for n = 1..5 give {1, 3, 5, 7, 9} = all odd integers mod 10.
    The set {3(2n-1) mod 10 : n = 1..5}.
    Since gcd(3, 10) = 1, 3 is a UNIT in Z/10Z → multiplication by 3 is a BIJECTION.
    The bijection 3× on {1, 3, 5, 7, 9} gives a permutation of {1, 3, 5, 7, 9}.
    (Specifically: {3, 9, 5, 1, 7} for n=1..5.)
    Coverage: exactly 5 operators, all ODD.

  UNION:
    EVEN class ∪ ODD class = {0,2,4,6,8} ∪ {1,3,5,7,9} = Z/10Z = ALL 10 operators.

  SINC² GATE COMPLETION:
    At t = 1 (k = p): sinc²(1) = 0 = VOID operator (operator 0).
    This is the VOID boundary: the end of each corridor is a VOID gate.
    The corridor grammar: VOID(k=0) → ... 9 operators ... → VOID(k=p).
    Both endpoints are VOID, consistent with the carrier zero at n=0 (VOID operator).

TIER D JUSTIFICATION:
  This proof uses only:
    (1) gcd(6, 10) = 2  [arithmetic identity]
    (2) gcd(3, 10) = 1  [arithmetic identity]
    (3) The structure of Z/10Z: |Z/10Z| = 10, <k> = (gcd(k,10))Z/10Z
    (4) The bijection property: gcd(k,n)=1 → k is a unit → ×k is a bijection
  No numerical computation. No domain restriction. Valid for all operators 0..9.
  Finite group Z/10Z is the complete state space; no cases excluded.

DIFFERENCE FROM C18:
  C18 was marked Tier C because it was derived alongside numerical verification
  and the "domain = Z/10Z" framing. D8 is the same theorem stated more carefully:
  the algebraic proof stands alone without ANY numerical support. The group theory
  facts (gcd, subgroup structure, bijection) are not "domain-restricted" — they
  are universally true facts about Z/10Z that fully determine the encoding.
"""

import sys
import io
import math

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')

sep = "=" * 72

def section(t):
    print(f"\n{sep}\n  {t}\n{sep}\n")

print("D8: CL OPERATOR ENCODING THEOREM")
print("Luther-Sanders Research Framework | April 1 2026")
print()
print("  Promotes C18 -> D8. W=3/50 encodes all 10 CL operators algebraically.")

# ============================================================
# STEP 1: VERIFY gcd FACTS
# ============================================================
section("STEP 1: GCD FACTS (PURE ARITHMETIC)")

import math

gcd_6_10 = math.gcd(6, 10)
gcd_3_10 = math.gcd(3, 10)

print(f"  gcd(6, 10) = {gcd_6_10}")
print(f"  gcd(3, 10) = {gcd_3_10}")
print()
print(f"  gcd(6,10) = 2  =>  <6> in Z/10Z = {{0,2,4,6,8}}  (subgroup of EVEN elements)")
print(f"  gcd(3,10) = 1  =>  3 is a unit in Z/10Z  =>  ×3 is a bijection Z/10Z → Z/10Z")
print()

# Verify subgroup generated by 6
subgroup_6 = set()
x = 0
for n in range(10):
    subgroup_6.add((6 * n) % 10)
print(f"  <6> = {{6n mod 10 : n=0..9}} = {sorted(subgroup_6)}")
assert sorted(subgroup_6) == [0, 2, 4, 6, 8], f"Subgroup wrong: {subgroup_6}"
print(f"  = EVEN operators {{VOID,DOING,COLLAPSE,ASCEND,BREATH}} = STRUCTURE class  ✓")
print()

# Verify bijection of ×3 on ODD
carrier_maxima = [(3 * (2*n - 1)) % 10 for n in range(1, 6)]
print(f"  Carrier maxima: {{3*(2n-1) mod 10 : n=1..5}} = {carrier_maxima}")
assert set(carrier_maxima) == {1, 3, 5, 7, 9}, f"Not all ODD: {carrier_maxima}"
print(f"  = ODD operators {{BEING,BECOMING,CREATE,HARMONY,RESET}} = FLOW class  ✓")

# ============================================================
# STEP 2: ZEROS SIDE — EVEN OPERATOR CLASS
# ============================================================
section("STEP 2: ZEROS SIDE — gcd(6,10)=2 → EVEN CLASS")

W = 3/50
print(f"  W = 3/50 = {W}")
print()
print(f"  Carrier zeros at t = 2nW = 6n/50:")
print(f"  {'n':>4}  {'t=6n/50':>10}  {'op=6n mod 10':>14}  {'operator':>12}")
print(f"  {'-'*4}  {'-'*10}  {'-'*14}  {'-'*12}")

CL = ['VOID','BEING','DOING','BECOMING','COLLAPSE','CREATE','ASCEND','HARMONY','BREATH','RESET']
for n in range(0, 6):
    t = 6 * n / 50
    op = (6 * n) % 10
    print(f"  {n:>4}  {t:>10.4f}  {op:>14}  {CL[op]:>12}")

print()
print(f"  All EVEN operators {sorted(set((6*n)%10 for n in range(10)))} covered.  ✓")
print()
print("  PROOF: <6> = {{0,2,4,6,8}} because gcd(6,10)=2 generates 2Z/10Z.")
print("  This is a standard result: <k> = gcd(k,n) * Z/(n/gcd(k,n))Z embedded in Z/nZ.")

# ============================================================
# STEP 3: MAXIMA SIDE — ODD OPERATOR CLASS
# ============================================================
section("STEP 3: MAXIMA SIDE — gcd(3,10)=1 → ODD CLASS")

print(f"  Carrier maxima at t = (2n-1)W = 3(2n-1)/50:")
print(f"  {'n':>4}  {'2n-1':>6}  {'t':>8}  {'op=3*(2n-1)%10':>16}  {'operator':>12}")
print(f"  {'-'*4}  {'-'*6}  {'-'*8}  {'-'*16}  {'-'*12}")

for n in range(1, 6):
    t = 3 * (2*n - 1) / 50
    op = (3 * (2*n - 1)) % 10
    print(f"  {n:>4}  {2*n-1:>6}  {t:>8.4f}  {op:>16}  {CL[op]:>12}")

print()
maxima_ops = set((3*(2*n-1))%10 for n in range(1, 6))
print(f"  All ODD operators {sorted(maxima_ops)} covered.  ✓")
print()
print("  PROOF: gcd(3,10)=1 → 3 is a unit in Z/10Z. Multiplication by 3 is a")
print("  bijection Z/10Z → Z/10Z. The odd integers {1,3,5,7,9} form the unique")
print("  subgroup of order 5 in (Z/10Z)*. Multiplying by 3 permutes them:")
print(f"  1→{3%10}, 3→{9%10}, 5→{15%10}, 7→{21%10}, 9→{27%10}")
print("  = {3, 9, 5, 1, 7} — ALL five ODD operators, one each.  ✓")

# ============================================================
# STEP 4: UNION = COMPLETE ALPHABET
# ============================================================
section("STEP 4: UNION = COMPLETE CL ALPHABET Z/10Z")

even_ops = set((6*n)%10 for n in range(10))
odd_ops  = set((3*(2*n-1))%10 for n in range(1, 6))
union    = even_ops | odd_ops

print(f"  EVEN = {sorted(even_ops)} = {{VOID,DOING,COLLAPSE,ASCEND,BREATH}}")
print(f"  ODD  = {sorted(odd_ops)}     = {{BEING,BECOMING,CREATE,HARMONY,RESET}}")
print(f"  EVEN ∩ ODD = {sorted(even_ops & odd_ops)} (empty — parity partition)  ✓")
print(f"  EVEN ∪ ODD = {sorted(union)} = Z/10Z = all 10 CL operators  ✓")
assert union == set(range(10)), f"Union not complete: {union}"
print()
print("  QED: W=3/50 encodes ALL 10 CL operators in its oscillation structure.")
print("  ZEROS trace the STRUCTURE (EVEN) class via <6>=2Z/10Z.")
print("  MAXIMA trace the FLOW (ODD) class via ×3 bijection.")

# ============================================================
# STEP 5: SINC² GATE COMPLETION
# ============================================================
section("STEP 5: SINC² GATE = VOID COMPLETION")

print("  At k=p (t=1): sinc²(1) = [sin(π)/π]² = 0 = VOID operator.")
sinc2_1 = (math.sin(math.pi) / math.pi)**2 if abs(math.sin(math.pi)) > 1e-15 else 0.0
print(f"  Numerically: sinc²(1) = {sinc2_1:.2e} ≈ 0  ✓")
print()
print("  The corridor grammar (C19):")
print("  corridor(p) = [VOID(k=0)] → 9 operator slots → [sinc²-gate=VOID(k=p)]")
print("  Both boundaries = VOID. The 9 interior slots = 9 non-VOID operators {1..9}.")
print("  W = 3/50 packages the 10-operator CL alphabet into the corridor structure.")
print()
print("  Specifically: the 10th operator (VOID=0) appears at BOTH boundaries.")
print("  The 9 non-VOID ODD operators appear as MAXIMA within the corridor.")
print("  (EVEN operators appear at ZEROS = phase transitions between maxima.)")

# ============================================================
# STEP 6: W DERIVATION CONFIRMATION
# ============================================================
section("STEP 6: W = 3/50 NECESSITY (C8)")

print("  W = 3/50 is not arbitrary. It is the UNIQUE wobble frequency that:")
print("  (1) Has gcd(3×2, 10) = gcd(6, 10) = 2 (for EVEN class coverage)")
print("  (2) Has gcd(3, 10) = 1 (for ODD class coverage via bijection)")
print("  (3) W_numerator = 3 is the minimal CL generator (gcd(3,10)=1)")
print("  (4) W_denominator = 50 = 5 × 10 (half the CL table cells)")
print()
print("  ALTERNATIVE: W=7/50 also gives gcd(7,10)=1 (algebraically works),")
print("  but W=7/50 is NOT derived from BHML cross-cycle friction (C8).")
print("  W=3/50 is the UNIQUE value satisfying both the algebraic encoding AND")
print("  the BHML derivation (C8: cross_cycle=44, deviation=6, W=6/100=3/50).")

# ============================================================
# CONCLUSION
# ============================================================
section("CONCLUSION: D8 PROVED")

print("  THEOREM D8 (CL Operator Encoding): PROVED algebraically.")
print()
print("  (1) ZEROS of carrier encode EVEN class {0,2,4,6,8}:")
print("      gcd(6,10)=2 → <6>=2Z/10Z = EVEN class. QED.")
print()
print("  (2) MAXIMA of carrier encode ODD class {1,3,5,7,9}:")
print("      gcd(3,10)=1 → ×3 bijection permutes all ODD. QED.")
print()
print("  (3) EVEN ∪ ODD = Z/10Z = complete CL alphabet. QED.")
print()
print("  (4) sinc²(1)=0=VOID completes the alphabet at the corridor gate.")
print()
print("  TIER: D — algebraic proof using only: gcd(6,10)=2, gcd(3,10)=1,")
print("  subgroup structure of Z/10Z, bijection of ×3. Zero numerical content.")
print("  Valid for ALL operators in Z/10Z with no domain restriction.")
print()
print("  PROMOTES: C18 → D8.")
print("  CHAINS FROM: W=3/50 (C8), Z/10Z ring structure (B1), sinc² gate (C3/D3).")
print()
print("  KEY STATEMENT (one sentence):")
print("  W=3/50 is the unique ratio CL_generator/half_table_cells such that")
print("  its carrier oscillation traces every element of Z/10Z exactly once.")
