/*
 * ao_earth.c -- D0 / Aperture / Position / Ground Truth
 *
 * All static data lives here (generated by gen_earth_data.py).
 * Plus a few lookup helpers.
 */
/*
 * Copyright (c) 2025-2026 Brayden Sanders / 7Site LLC
 * Licensed under the 7Site Human Use License v1.0
 * See LICENSE file in project root for full terms.
 *
 * FREE for humans for personal/recreational use.
 * NO commercial or government use without written agreement.
 */


#include "ao_earth.h"
#include <string.h>
#include <stdlib.h>
#include <math.h>

/* ── Generated data tables ── */
#include "ao_earth_data.inc"

/* ── CL shell lookup ── */
const int8_t (*ao_cl_shell(int shell))[10]
{
    switch (shell) {
        case 22: return ao_cl_22;
        case 44: return ao_cl_44;
        case 72: return ao_cl_72;
        default: return ao_cl_44; /* default to Becoming */
    }
}

int ao_compose(int a, int b, int shell)
{
    const int8_t (*table)[10] = ao_cl_shell(shell);
    if (a < 0 || a >= AO_NUM_OPS || b < 0 || b >= AO_NUM_OPS)
        return AO_HARMONY;
    return table[a][b];
}

/* ── Bump detection (lazy-init LUT for O(1)) ── */
int ao_is_bump(int row, int col)
{
    if (!ao_bump_lut_init) {
        int i;
        for (i = 0; i < AO_NUM_BUMPS; i++)
            ao_bump_lut[ao_bumps[i].row][ao_bumps[i].col] = 1;
        ao_bump_lut_init = 1;
    }
    if (row < 0 || row >= 10 || col < 0 || col >= 10)
        return 0;
    return ao_bump_lut[row][col];
}

/* ── Reverse voice lookup (binary search) ── */
static int ao_reverse_cmp(const void* key, const void* entry)
{
    return strcmp((const char*)key, ((const AO_ReverseEntry*)entry)->word);
}

const AO_ReverseEntry* ao_reverse_lookup(const char* word)
{
    return (const AO_ReverseEntry*)bsearch(
        word, ao_reverse_index, (size_t)ao_reverse_index_size,
        sizeof(AO_ReverseEntry), ao_reverse_cmp
    );
}

/* ── Classify 5D vector into operator (argmax + sign) ── */
int ao_classify_5d(const float vec[5])
{
    int best_dim = 0;
    float best_abs = 0.0f;
    int i;

    for (i = 0; i < 5; i++) {
        float a = vec[i] < 0.0f ? -vec[i] : vec[i];
        if (a > best_abs) {
            best_abs = a;
            best_dim = i;
        }
    }

    if (best_abs < 1e-12f)
        return AO_HARMONY; /* zero vector = perfect coherence */

    return vec[best_dim] >= 0.0f
        ? ao_d2_op_map[best_dim][0]
        : ao_d2_op_map[best_dim][1];
}
