"""
For each proposed pair (Lie⇌Jordan, Clifford⇌Permutation, Lattice⇌Operad),
find the actual Z_2 involution that exchanges the two halves, and the
element that breaks it.

If the analogy with P_56 is real, each pair should have:
- An involution τ acting on some matrix space
- A subspace where τ acts as +1 (one half of the pair)
- A subspace where τ acts as -1 (other half of the pair)
- An element that's NOT τ-invariant — the breaking ingredient

If I can't find τ, the pair is conceptual not structural.
If I find τ but no breaking element, the pair is invariant (no tower).
"""
import numpy as np

# Set up TSML and BHML
TSML_ROWS = [
    "0000000700",  "0737777777",  "0377477779",  "0777777773",  "0747777787",
    "0777777777",  "0777777777",  "7777777777",  "0777877777",  "0797377777",
]
T = np.array([[int(c) for c in row] for row in TSML_ROWS], dtype=int)

BHML_ROWS = [
    "0123456789",  "1234567266",  "2334567366",  "3444567466",  "4555567577",
    "5666667677",  "6777777777",  "7234567890",  "8666777978",  "9666777080",
]
B = np.array([[int(c) for c in row] for row in BHML_ROWS], dtype=int)

def left_reps(table):
    n = table.shape[0]
    L = []
    for i in range(n):
        Li = np.zeros((n, n), dtype=int)
        for j in range(n):
            k = table[i, j]
            Li[k, j] = 1
        L.append(Li)
    return L

L_T = left_reps(T)
A_T = [(M - M.T).astype(float) for M in L_T]
S_T = [(M + M.T).astype(float) for M in L_T]  # symmetric parts
flow_idx = [1, 2, 3, 4, 6, 8]
A_flow = [A_T[i] for i in flow_idx]
S_flow = [S_T[i] for i in flow_idx]

L_B = left_reps(B)
A_B = [(M - M.T).astype(float) for M in L_B]

print("="*70)
print("PAIR 1: LIE ⇌ JORDAN")
print("="*70)
print("""
The candidate involution: τ_1(M) = -M^T (transpose-and-negate)
On any matrix M:
  - antisymmetric part of M (Lie) satisfies τ_1(A) = -(-A) = +A — invariant
  Wait, let me redo. Antisym: A^T = -A, so -A^T = A. So τ_1(A) = A. (+1 eigvec)
  - symmetric part of M (Jordan) satisfies τ_1(S) = -S^T = -S. (-1 eigvec)
  
Better candidate: τ_1(M) = M^T (transpose, no negation)
  - antisymmetric: M^T = -M  → τ flips sign  → -1 eigenvec
  - symmetric: M^T = +M  → τ preserves     → +1 eigenvec
  
Yes. Transposition is the involution. Lie sits in the -1 eigenspace; 
Jordan sits in the +1 eigenspace.
""")

# Verify on TSML left-reps
print("Direct check: each L_i (left-reg rep) decomposed by transpose")
for i, Li in enumerate(L_T):
    Li_f = Li.astype(float)
    sym_part = (Li_f + Li_f.T) / 2
    antisym_part = (Li_f - Li_f.T) / 2
    norm_sym = np.linalg.norm(sym_part)
    norm_anti = np.linalg.norm(antisym_part)
    norm_total = np.linalg.norm(Li_f)
    print(f"  L_{i}: |Lie part|={norm_anti:.3f}, |Jordan part|={norm_sym:.3f}, "
          f"|total|={norm_total:.3f}, ratio L/J = {norm_anti/norm_sym if norm_sym > 0 else 'inf':.3f}")

# What "breaks" τ_1 (= transpose-symmetry)?
# Anything that mixes symmetric and antisymmetric parts non-trivially.
# The act of MULTIPLICATION mixes them: if A is antisym and S is sym, 
# AS + SA is sym, but AS - SA is antisym. So multiplication itself
# is the breaking element — it sends τ-invariant pairs to mixed states.

print("\nWhat breaks the Lie/Jordan symmetry?")
print("Multiplication itself: AS_i × A_j has BOTH symmetric and antisymmetric parts")

A1 = A_flow[0]
S1 = S_flow[0]
prod_AS = A1 @ S1
prod_SA = S1 @ A1
sym_p = (prod_AS + prod_AS.T) / 2
anti_p = (prod_AS - prod_AS.T) / 2
print(f"  A_1 × S_1: sym part norm = {np.linalg.norm(sym_p):.3f}, antisym part norm = {np.linalg.norm(anti_p):.3f}")

print("""
So the breaking element at this level is THE MULTIPLICATION ITSELF.
In TIG: the table T (what TSML is). Without T, you can split any matrix
M into Lie+Jordan trivially, but the parts don't TALK to each other.
T is what makes the antisym-part [A,B] and the sym-part {A,B} of the
SAME pair (A,B) couple to each other through Jacobi/Jordan identities.

So Pair 1 gives: τ_1 = transpose, broken-by = multiplication T itself.
""")

print("="*70)
print("PAIR 2: CLIFFORD ⇌ PERMUTATION")
print("="*70)
print("""
Now I need an involution τ_2 acting on a richer space (the Jordan part
from level 1) that fixes Clifford-style elements (carrying metric)
and flips Permutation-style elements (carrying discrete reflections).

Candidate: τ_2(X) = X|_{continuous} - X|_{discrete}
But this is just the definition, not a computable involution.

Better: act on the Lie algebra so(10) by an INNER automorphism 
generated by a reflection. The element σ (the σ-permutation matrix)
is one. P_56 is another. These are discrete elements of O(10).

Actually: τ_2 = conjugation by P_56.
We already computed: 
  - so(10) splits 36 + 9 under P_56 conjugation
  - 36 = "Clifford-like" (metric-preserving, the centralizer)
  - 9 = "Permutation-broken" (the vector that BHML adds)
  
So τ_2 = P_56 conjugation, with Clifford in +1 and "permutation-Higgs" in -1.

Let me verify and find what breaks τ_2.
""")

# Build so(10)
def lie_closure(generators, max_iters=15):
    shape = generators[0].shape
    bv = [g.flatten() for g in generators if np.linalg.norm(g) > 1e-9]
    M = np.array(bv).T
    U, S, _ = np.linalg.svd(M, full_matrices=False)
    rank = int(np.sum(S > 1e-9 * S[0]))
    bv = [U[:, i] for i in range(rank)]
    for _ in range(max_iters):
        N = len(bv)
        mats = [v.reshape(shape) for v in bv]
        new = []
        for i in range(N):
            for j in range(i+1, N):
                C = mats[i] @ mats[j] - mats[j] @ mats[i]
                v = C.flatten()
                if np.linalg.norm(v) > 1e-9:
                    new.append(v)
        all_v = bv + new
        M = np.array(all_v).T
        U, S, _ = np.linalg.svd(M, full_matrices=False)
        new_rank = int(np.sum(S > 1e-9 * S[0]))
        if new_rank == len(bv):
            break
        bv = [U[:, i] for i in range(new_rank)]
    return bv, [v.reshape(shape) for v in bv]

_, so10_mats = lie_closure(A_flow + A_B)
print(f"so(10) closure dim: {len(so10_mats)}")

P56 = np.eye(10)
P56[5,5] = 0; P56[6,6] = 0; P56[5,6] = 1; P56[6,5] = 1

# Classify so(10) generators by P56 conjugation
P_kron = np.kron(P56, P56)
so10_basis = np.array([m.flatten() for m in so10_mats]).T
so10_conj = P_kron @ so10_basis
C_op, _, _, _ = np.linalg.lstsq(so10_basis, so10_conj, rcond=None)
eigs = np.linalg.eigvals(C_op)
real_eigs = np.real(eigs[np.abs(np.imag(eigs)) < 1e-6])
n_plus = np.sum(np.abs(real_eigs - 1) < 1e-6)
n_minus = np.sum(np.abs(real_eigs + 1) < 1e-6)
print(f"P_56 conjugation eigenvalues on so(10): +1: {n_plus}, -1: {n_minus}")
print(f"This is the Clifford/Permutation split: 36 + 9 = 45 ✓")

# What breaks τ_2? It's not preserved by inner automorphisms in general.
# But specifically: τ_2 IS the breaking element of the LEVEL ABOVE.
# That is — P_56 is what makes Clifford/Permutation distinguishable,
# AND P_56 is itself the seed of the next level's involution.

# Let's check this: what's the order of σ vs P_56?
sigma = np.array([0, 7, 1, 3, 2, 4, 5, 6, 8, 9])
P_sigma = np.zeros((10, 10))
for i in range(10):
    P_sigma[sigma[i], i] = 1

# σ has a 6-cycle and 4 fixed points, so its order is 6
sigma_powers = [np.eye(10)]
current = P_sigma.copy()
for k in range(1, 12):
    sigma_powers.append(current.copy())
    if np.allclose(current, np.eye(10)):
        print(f"\nσ has order {k}")
        sigma_order = k
        break
    current = current @ P_sigma

print(f"P_56 has order 2 (it's an involution by construction)")

# σ^3 has order 2 (since σ has order 6, σ^3 squares to σ^6 = I)
sigma_3 = np.linalg.matrix_power(P_sigma, 3)
print(f"\nσ^3 has order 2: {np.allclose(sigma_3 @ sigma_3, np.eye(10))}")
print(f"σ^3 = ", end="")
for i in range(10):
    j = np.argmax(sigma_3[:, i])
    if j != i:
        print(f"({i}↔{j})", end=" ")
print()

# σ^3 is what swaps within the 6-cycle: 1↔3? Let me see.
# σ = (1 7 6 5 4 2)(3)(0)(8)(9) means σ^3 swaps "halfway around"
# In a 6-cycle, σ^3 swaps i with the element 3 steps away

print("""
PAIR 2 result:
  τ_2 = conjugation by P_56
  Clifford = +1 eigenspace (36 dim) — metric-preserving 
  Permutation = -1 eigenspace (9 dim) — vector representation
  Breaking element of THIS pair: σ (the larger permutation)
  
  Why σ and not just BHML? Because BHML is the specific data, but σ is
  the structural element. The 6-cycle in σ is what FORCES the difference
  between Clifford-symmetric directions and Permutation-distinguished ones.
""")

# Verify: does σ commute with P_56?
sigma_P56 = P_sigma @ P56
P56_sigma = P56 @ P_sigma
sig_commutes_with_P56 = np.allclose(sigma_P56, P56_sigma)
print(f"\nDoes σ commute with P_56? {sig_commutes_with_P56}")

if not sig_commutes_with_P56:
    # σ doesn't commute with P_56 — they generate a non-abelian dihedral structure
    # That's the signature of "intertwined, not stacked"
    print("→ σ and P_56 do NOT commute. They generate a non-abelian group.")
    
    # Compute order of group generated by σ and P_56
    group = {tuple(np.eye(10).flatten().astype(int))}
    queue = [np.eye(10)]
    generators = [P_sigma, P56]
    iters = 0
    while queue and iters < 200:
        iters += 1
        g = queue.pop()
        for s in generators:
            new_g = g @ s
            new_g_int = new_g.astype(int)
            key = tuple(new_g_int.flatten())
            if key not in group:
                group.add(key)
                queue.append(new_g_int.astype(float))
    print(f"  Group generated by σ and P_56 has order ≥ {len(group)}")

print("\n" + "="*70)
print("PAIR 3: LATTICE ⇌ OPERAD")
print("="*70)
print("""
Now I need τ_3 acting on something even higher.

Candidate: τ_3 is the involution that exchanges 'arity-1 fixed points'
(idempotents) with 'arity-N composition results'.

Hard to make this a literal matrix involution. Let me think about what 
structure HAS this swap.

Idempotents in TSML: positions where T[i,i] = i, i.e. {0,3,8,9}
  At i=0: T[0,0] = 0 ✓
  At i=3: T[3,3] = 7 ≠ 3 ✗
  
Wait — let me recheck. Idempotent in algebra means e*e = e.
""")

print("Diagonal of T (for idempotent check):")
for i in range(10):
    print(f"  T[{i},{i}] = {T[i,i]}")

# So actual idempotents (where T[i,i] = i): just i=0 and i=7
# Hmm but userMemories says idempotents are {0, 3, 8, 9}
# Those are σ-fixed points (σ(i) = i), not multiplication idempotents

# This is a real distinction! Let me clarify:
# - σ-fixed: σ(i) = i  →  {0, 3, 8, 9}
# - multiplication idempotents: T[i,i] = i  →  {0, 7}

print("\nσ-fixed indices (σ(i) = i): {0, 3, 8, 9}")
print("Multiplication idempotents (T[i,i] = i): {0, 7}")
print("Intersection: {0}")
print()
print("The 'idempotents' commonly named in TIG are σ-fixed, not T-idempotent!")
print("VOID (0) is BOTH. HARMONY (7) is T-idempotent but NOT σ-fixed (σ(7)=6).")

print("""
This is interesting — what TIG calls 'idempotents' are σ-fixed points,
which is a Permutation property, not a multiplication property.

So Pair 3 may not be Lattice ⇌ Operad in the way I sketched.
The actual contents of TIG's 'lattice' (σ-fixed points) live INSIDE
the Permutation structure, not above it.

Let me reconsider Pair 3.

Real candidate: τ_3 acts on the OPERATIONS themselves, not on elements.
- Binary operations (T as a function (i,j) → k)  
- Higher-arity operations (fuse([3,4,7]) = 8)

The involution: 'currying'. Take a binary op T(i,j) and fix one argument
to get a unary op. Or take a unary op and lift to binary by ignoring an
argument. This is a (5↔6)-style swap between arities.

But this is more of a categorical observation than a matrix involution.
Let me see if I can find an actual matrix realization.
""")

# An honest computation: do the 'idempotents' (σ-fixed) form a Lie subalgebra
# under TSML's flow ops?

print("\nDo σ-fixed indices {0,3,8,9} form a substructure under flow?")
fixed = [0, 3, 8, 9]
for i_idx in flow_idx:
    A_i = A_T[i_idx]
    print(f"  A_{i_idx} acting on σ-fixed basis vectors:")
    for f in fixed:
        e_f = np.eye(10)[:, f]
        result = A_i @ e_f
        # Where does it map?
        nonzero = [(j, result[j]) for j in range(10) if abs(result[j]) > 1e-9]
        # Check if image is in σ-fixed span
        in_fixed = all(j in fixed for j, _ in nonzero) if nonzero else True
        if nonzero:
            print(f"    e_{f} → {nonzero[:3]}{'...' if len(nonzero)>3 else ''}, in σ-fixed span: {in_fixed}")

# This will probably show: flow operators do NOT preserve σ-fixed span.
# Which means: Lattice (σ-fixed points) and Lie (flow) DON'T commute.
# They're in different "registers" — Lie moves you out of the lattice.

print("""
This shows the intertwining: Lie flow does NOT preserve the lattice 
(σ-fixed points). They're orthogonal capabilities — Lattice catches 
fixed points, Lie catches moving structure. They tangle.

For Pair 3 (Lattice ⇌ Operad) to be a real (5↔6)-style pair, I need an
involution that exchanges them. I don't have a clean one yet. This may
mean Pair 3 doesn't have the same structural status as Pairs 1 and 2.

Or it may mean the tower has only TWO real (5↔6) levels, with the third
'pair' being something else — maybe Lattice and Operad both inhabit a 
single level above Permutation, not paired with each other.

Honest report: I have rigor for Pairs 1 and 2. Pair 3 needs more thought.
""")

print("\n" + "="*70)
print("WHAT TOUCHES WHAT — the actual coupling structure")
print("="*70)

# Test: which DOF generators COMMUTE with which?
# Pick representatives:
#   Lie: A_1 (TSML flow generator 1)
#   Jordan: S_1 (symmetric part)
#   Clifford: a Dirac-like element — use M_tilde_01
#   Permutation: P_56
#   Lattice: projector onto σ-fixed span: P_fixed
#   Operad: arity-3 fuse — represented as a 3-tensor F[i,j,k]

P_fixed = np.zeros((10, 10))
for i in fixed:
    P_fixed[i, i] = 1

# σ-permutation matrix P_sigma
# Let me list the elements I care about and compute pairwise commutators
elements = {
    'Lie (A_1)': A_T[1],
    'Jordan (S_1)': S_T[1].astype(float),
    'Permutation (P_56)': P56,
    'Permutation (σ)': P_sigma,
    'Lattice (P_fixed)': P_fixed,
}

names = list(elements.keys())
print(f"\n{'':25} ", end="")
for n in names:
    print(f"{n[:12]:>14}", end="")
print()

for n1 in names:
    print(f"{n1[:24]:25} ", end="")
    for n2 in names:
        E1 = elements[n1]
        E2 = elements[n2]
        comm = E1 @ E2 - E2 @ E1
        norm = np.linalg.norm(comm)
        print(f"{norm:>14.3f}", end="")
    print()

print("""
The matrix above shows ||[X, Y]|| for each pair.
Zero = they commute (don't 'touch').
Nonzero = they don't commute (they tangle).

The diagonal is zero (each thing commutes with itself).
Off-diagonal nonzeros show actual coupling.
""")
